# Generated by Django 6.0.5 on 2026-05-29 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HesapPlani',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('hesap_kodu', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='hesap kodu')),
                ('hesap_adi', models.CharField(max_length=200, verbose_name='hesap adı')),
                ('rapor_grubu', models.CharField(choices=[('BILANCO', 'Bilanço'), ('GELIR_TABLOSU', 'Gelir Tablosu'), ('MALIYET', 'Maliyet (7xx)')], max_length=20, verbose_name='rapor grubu')),
                ('rapor_kalemi', models.CharField(blank=True, max_length=20, verbose_name='rapor kalemi')),
                ('parasal', models.BooleanField(blank=True, null=True, verbose_name='parasal')),
                ('aktif', models.BooleanField(default=True, verbose_name='aktif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'hesap',
                'verbose_name_plural': 'hesap planı',
                'db_table': 'hesap_plani',
                'ordering': ['hesap_kodu'],
            },
        ),
    ]
