# Generated by Django 6.0.5 on 2026-05-29 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kur',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('tarih', models.DateField(primary_key=True, serialize=False, verbose_name='tarih')),
                ('usd_alis', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='USD alış')),
                ('eur_alis', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='EUR alış')),
                ('gbp_alis', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='GBP alış')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'kur',
                'verbose_name_plural': 'kurlar',
                'db_table': 'kur',
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='YevmiyeFisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('yil', models.IntegerField(verbose_name='mali yıl')),
                ('fis_no', models.PositiveIntegerField(verbose_name='fiş no')),
                ('tarih', models.DateField(verbose_name='muhasebe tarihi')),
                ('aciklama', models.CharField(blank=True, max_length=500, verbose_name='açıklama')),
                ('kaynak', models.CharField(choices=[('MANUEL', 'Manuel')], default='MANUEL', max_length=20, verbose_name='kaynak')),
                ('kur_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='USD kuru')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'yevmiye fişi',
                'verbose_name_plural': 'yevmiye fişleri',
                'db_table': 'yevmiye_fisi',
                'ordering': ['yil', 'fis_no'],
            },
        ),
        migrations.CreateModel(
            name='YevmiyeSatir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('borc', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='borç (TL)')),
                ('alacak', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='alacak (TL)')),
                ('islem_pb', models.CharField(choices=[('TRY', 'TRY'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='TRY', max_length=3, verbose_name='işlem PB')),
                ('islem_tutari', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='işlem tutarı')),
                ('islem_kuru', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='işlem kuru')),
                ('aciklama', models.CharField(blank=True, max_length=500, verbose_name='açıklama')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('fis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satirlar', to='core.yevmiyefisi', verbose_name='fiş')),
                ('hesap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='satirlar', to='core.hesapplani', verbose_name='hesap')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'yevmiye satırı',
                'verbose_name_plural': 'yevmiye satırları',
                'db_table': 'yevmiye_satir',
                'ordering': ['fis', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='yevmiyefisi',
            constraint=models.UniqueConstraint(fields=('yil', 'fis_no'), name='uq_yevmiye_yil_fisno'),
        ),
    ]
