# Generated by Django 6.0.5 on 2026-05-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_kur_yevmiyefisi_yevmiyesatir_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kur',
            name='eur_alis',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='EUR alış'),
        ),
        migrations.AlterField(
            model_name='kur',
            name='gbp_alis',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='GBP alış'),
        ),
    ]
