# Generated by Django 6.0.5 on 2026-05-31 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ekranyetki'),
    ]

    operations = [
        migrations.AddField(
            model_name='kur',
            name='eur_efektif_alis',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='EUR MB efektif alış'),
        ),
        migrations.AddField(
            model_name='kur',
            name='eur_efektif_satis',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='EUR MB efektif satış'),
        ),
        migrations.AddField(
            model_name='kur',
            name='eur_satis',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='EUR MB satış'),
        ),
        migrations.AddField(
            model_name='kur',
            name='gbp_efektif_alis',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='GBP MB efektif alış'),
        ),
        migrations.AddField(
            model_name='kur',
            name='gbp_efektif_satis',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='GBP MB efektif satış'),
        ),
        migrations.AddField(
            model_name='kur',
            name='gbp_satis',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='GBP MB satış'),
        ),
        migrations.AddField(
            model_name='kur',
            name='usd_efektif_alis',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='USD MB efektif alış'),
        ),
        migrations.AddField(
            model_name='kur',
            name='usd_efektif_satis',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='USD MB efektif satış'),
        ),
        migrations.AddField(
            model_name='kur',
            name='usd_satis',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='USD MB satış'),
        ),
    ]
