# Generated by Django 6.0.5 on 2026-05-31 22:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_kur_eur_efektif_alis_kur_eur_efektif_satis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='yevmiyefisi',
            index=models.Index(fields=['tarih'], name='idx_yevmiye_tarih'),
        ),
    ]
