# Generated by Django 6.0.5 on 2026-05-31 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_yevmiyefisi_idx_yevmiye_tarih'),
    ]

    operations = [
        migrations.AddField(
            model_name='hesapplani',
            name='ust_hesap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alt_hesaplar', to='core.hesapplani', verbose_name='üst hesap'),
        ),
    ]
