# Generated by Django 6.0.5 on 2026-06-01 11:47

import django.contrib.postgres.indexes
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_hesapplani_ust_hesap'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # gin_trgm_ops için pg_trgm uzantısı (PG13+ trusted; DB sahibi kurabilir).
        TrigramExtension(),
        migrations.AddIndex(
            model_name='hesapplani',
            index=django.contrib.postgres.indexes.GinIndex(fields=['hesap_adi'], name='gin_hesap_adi', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='hesapplani',
            index=django.contrib.postgres.indexes.GinIndex(fields=['hesap_kodu'], name='gin_hesap_kodu', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='yevmiyefisi',
            index=django.contrib.postgres.indexes.GinIndex(fields=['aciklama'], name='gin_fis_aciklama', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='kur',
            constraint=models.CheckConstraint(condition=models.Q(('usd_alis__gt', 0)), name='ck_kur_usd_alis_gt0'),
        ),
        migrations.AddConstraint(
            model_name='yevmiyefisi',
            constraint=models.CheckConstraint(condition=models.Q(('kur_usd__isnull', True), ('kur_usd__gt', 0), _connector='OR'), name='ck_fis_kur_usd_gt0'),
        ),
        migrations.AddConstraint(
            model_name='yevmiyesatir',
            constraint=models.CheckConstraint(condition=models.Q(('borc__gte', 0)), name='ck_satir_borc_gte0'),
        ),
        migrations.AddConstraint(
            model_name='yevmiyesatir',
            constraint=models.CheckConstraint(condition=models.Q(('alacak__gte', 0)), name='ck_satir_alacak_gte0'),
        ),
        migrations.AddConstraint(
            model_name='yevmiyesatir',
            constraint=models.CheckConstraint(condition=models.Q(('borc', 0), ('alacak', 0), _connector='OR'), name='ck_satir_tek_taraf'),
        ),
        migrations.AddConstraint(
            model_name='yevmiyesatir',
            constraint=models.CheckConstraint(condition=models.Q(('islem_tutari__gte', 0)), name='ck_satir_islem_tutari_gte0'),
        ),
        migrations.AddConstraint(
            model_name='yevmiyesatir',
            constraint=models.CheckConstraint(condition=models.Q(('islem_kuru__gt', 0)), name='ck_satir_islem_kuru_gt0'),
        ),
    ]
