# Generated by Django 6.0.5 on 2026-06-01 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_hesapplani_gin_hesap_adi_hesapplani_gin_hesap_kodu_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Birim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('ad', models.CharField(max_length=50, verbose_name='ad')),
                ('kisa_ad', models.CharField(max_length=10, verbose_name='kısa ad')),
                ('ondalik', models.PositiveSmallIntegerField(default=0, verbose_name='ondalık hane')),
                ('aktif', models.BooleanField(default=True, verbose_name='aktif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'birim',
                'verbose_name_plural': 'birimler',
                'db_table': 'birim',
                'ordering': ['ad'],
                'constraints': [models.CheckConstraint(condition=models.Q(('ondalik__lte', 6)), name='ck_birim_ondalik_0_6')],
            },
        ),
    ]
