# Generated by Django 6.0.5 on 2026-06-01 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_kategori'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaturaTipi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('ad', models.CharField(max_length=100, verbose_name='ad')),
                ('yon', models.CharField(choices=[('SATIS', 'Satış'), ('ALIS', 'Alış')], max_length=5, verbose_name='yön')),
                ('sira', models.PositiveSmallIntegerField(default=0, verbose_name='sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='aktif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'fatura tipi',
                'verbose_name_plural': 'fatura tipleri',
                'db_table': 'fatura_tipi',
                'ordering': ['sira', 'ad'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('silindi', False)), fields=('ad',), name='uq_fatura_tipi_ad_aktif')],
            },
        ),
    ]
