# Generated by Django 6.0.5 on 2026-06-01 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_faturatipi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriHesap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
            ],
            options={
                'verbose_name': 'kategori hesap bağı',
                'verbose_name_plural': 'kategori hesap bağları',
                'db_table': 'kategori_hesap',
            },
        ),
        migrations.RemoveField(
            model_name='kategori',
            name='hesap',
        ),
        migrations.AddField(
            model_name='kategori',
            name='kod',
            field=models.CharField(default='', max_length=30, verbose_name='kod'),
        ),
        migrations.AddConstraint(
            model_name='kategori',
            constraint=models.UniqueConstraint(condition=models.Q(('silindi', False)), fields=('kod',), name='uq_kategori_kod_aktif'),
        ),
        migrations.AddField(
            model_name='kategorihesap',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan'),
        ),
        migrations.AddField(
            model_name='kategorihesap',
            name='fatura_tipi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kategori_baglari', to='core.faturatipi', verbose_name='fatura tipi'),
        ),
        migrations.AddField(
            model_name='kategorihesap',
            name='hesap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kategori_baglari', to='core.hesapplani', verbose_name='muhasebe hesabı'),
        ),
        migrations.AddField(
            model_name='kategorihesap',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hesap_baglari', to='core.kategori', verbose_name='kategori'),
        ),
        migrations.AddField(
            model_name='kategorihesap',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen'),
        ),
        migrations.AddConstraint(
            model_name='kategorihesap',
            constraint=models.UniqueConstraint(fields=('kategori', 'fatura_tipi'), name='uq_kategori_fatura_tipi'),
        ),
    ]
