# Generated by Django 6.0.5 on 2026-06-01 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_kategorihesap_remove_kategori_hesap_kategori_kod_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='kategori',
            name='uq_kategori_kod_aktif',
        ),
        migrations.AddConstraint(
            model_name='kategori',
            constraint=models.UniqueConstraint(condition=models.Q(('silindi', False)), fields=('ust', 'kod'), name='uq_kategori_ust_kod_aktif', nulls_distinct=False),
        ),
    ]
