# Generated by Django 6.0.5 on 2026-06-01 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_kategori_uq_kategori_kod_aktif_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birim',
            name='aktif',
        ),
        migrations.RemoveField(
            model_name='faturatipi',
            name='aktif',
        ),
        migrations.AddConstraint(
            model_name='birim',
            constraint=models.UniqueConstraint(condition=models.Q(('silindi', False)), fields=('ad',), name='uq_birim_ad_aktif'),
        ),
        migrations.AddConstraint(
            model_name='birim',
            constraint=models.UniqueConstraint(condition=models.Q(('silindi', False)), fields=('kisa_ad',), name='uq_birim_kisa_ad_aktif'),
        ),
    ]
