# Generated by Django 6.0.5 on 2026-06-01 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_birim_aktif_remove_faturatipi_aktif_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('kod', models.CharField(max_length=40, verbose_name='kod')),
                ('ad', models.CharField(max_length=200, verbose_name='ad')),
                ('cevirici', models.DecimalField(decimal_places=6, default=1, max_digits=18, verbose_name='çevirici')),
                ('kdv_orani', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='KDV oranı (%)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('fatura_birimi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fatura_stoklari', to='core.birim', verbose_name='fatura birimi')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stoklar', to='core.kategori', verbose_name='alt kategori')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
                ('uretim_birimi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uretim_stoklari', to='core.birim', verbose_name='üretim birimi')),
            ],
            options={
                'verbose_name': 'stok',
                'verbose_name_plural': 'stoklar',
                'db_table': 'stok',
                'ordering': ['kod'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('silindi', False)), fields=('kod',), name='uq_stok_kod_aktif'), models.CheckConstraint(condition=models.Q(('cevirici__gt', 0)), name='ck_stok_cevirici_gt0'), models.CheckConstraint(condition=models.Q(('kdv_orani__gte', 0)), name='ck_stok_kdv_gte0')],
            },
        ),
    ]
