# Generated by Django 6.0.5 on 2026-06-01 22:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_stok'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stok',
            name='kritik_stok',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='kritik stok seviyesi'),
        ),
        migrations.AddField(
            model_name='stok',
            name='tedarikci',
            field=models.CharField(blank=True, max_length=200, verbose_name='tedarikçi (cari)'),
        ),
        migrations.AddField(
            model_name='stok',
            name='tevkifat_orani',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='tevkifat oranı (%)'),
        ),
        migrations.AddConstraint(
            model_name='stok',
            constraint=models.CheckConstraint(condition=models.Q(('tevkifat_orani__gte', 0)), name='ck_stok_tevkifat_gte0'),
        ),
        migrations.AddConstraint(
            model_name='stok',
            constraint=models.CheckConstraint(condition=models.Q(('kritik_stok__gte', 0)), name='ck_stok_kritik_gte0'),
        ),
    ]
