# Generated by Django 6.0.5 on 2026-06-01 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_stok_kritik_stok_stok_tedarikci_stok_tevkifat_orani_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ulke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('kod', models.CharField(max_length=2, verbose_name='ISO kod')),
                ('ad', models.CharField(max_length=80, verbose_name='ad')),
                ('ad_en', models.CharField(blank=True, max_length=80, verbose_name='İngilizce ad')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'ülke',
                'verbose_name_plural': 'ülkeler',
                'db_table': 'ulke',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Sehir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('kod', models.CharField(blank=True, max_length=10, verbose_name='plaka/kod')),
                ('ad', models.CharField(max_length=80, verbose_name='ad')),
                ('ad_en', models.CharField(blank=True, max_length=80, verbose_name='İngilizce ad')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
                ('ulke', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sehirler', to='core.ulke', verbose_name='ülke')),
            ],
            options={
                'verbose_name': 'şehir',
                'verbose_name_plural': 'şehirler',
                'db_table': 'sehir',
                'ordering': ['ulke', 'ad'],
            },
        ),
        migrations.AddConstraint(
            model_name='ulke',
            constraint=models.UniqueConstraint(condition=models.Q(('silindi', False)), fields=('kod',), name='uq_ulke_kod_aktif'),
        ),
        migrations.AddConstraint(
            model_name='sehir',
            constraint=models.UniqueConstraint(condition=models.Q(('silindi', False)), fields=('ulke', 'ad'), name='uq_sehir_ulke_ad_aktif'),
        ),
    ]
