# Generated by Django 6.0.5 on 2026-06-01 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_ulke_sehir_ulke_uq_ulke_kod_aktif_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CariKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('ad', models.CharField(max_length=100, verbose_name='ad')),
                ('kod', models.CharField(max_length=10, verbose_name='kod')),
                ('aciklama', models.TextField(blank=True, verbose_name='açıklama')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
                ('ust', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alt_kategoriler', to='core.carikategori', verbose_name='üst kategori')),
            ],
            options={
                'verbose_name': 'cari kategori',
                'verbose_name_plural': 'cari kategorileri',
                'db_table': 'cari_kategori',
                'ordering': ['kod'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('silindi', False)), fields=('ust', 'kod'), name='uq_carikat_ust_kod_aktif', nulls_distinct=False), models.UniqueConstraint(condition=models.Q(('silindi', False)), fields=('ust', 'ad'), name='uq_carikat_ust_ad_aktif', nulls_distinct=False)],
            },
        ),
    ]
