# Generated by Django 6.0.5 on 2026-06-07 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_carikategori'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('kod', models.CharField(max_length=30, verbose_name='cari kodu')),
                ('unvan', models.CharField(max_length=200, verbose_name='unvan / ad soyad')),
                ('kisa_ad', models.CharField(blank=True, max_length=80, verbose_name='kısa ad')),
                ('vergi_dairesi', models.CharField(blank=True, max_length=100, verbose_name='vergi dairesi')),
                ('vkn_tckn', models.CharField(blank=True, db_index=True, max_length=15, verbose_name='VKN / TCKN')),
                ('tax_id', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Tax ID (yurtdışı)')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='telefon')),
                ('telefon_2', models.CharField(blank=True, max_length=20, verbose_name='telefon 2')),
                ('eposta', models.EmailField(blank=True, max_length=254, verbose_name='e-posta')),
                ('web', models.URLField(blank=True, verbose_name='web')),
                ('kep_adresi', models.CharField(blank=True, max_length=100, verbose_name='KEP')),
                ('adres', models.TextField(blank=True, verbose_name='adres')),
                ('posta_kodu', models.CharField(blank=True, max_length=15, verbose_name='posta kodu')),
                ('sevk_farkli', models.BooleanField(default=False, verbose_name='sevk adresi farklı')),
                ('sevk_adres', models.TextField(blank=True, verbose_name='sevk adres')),
                ('sevk_posta_kodu', models.CharField(blank=True, max_length=15, verbose_name='sevk posta kodu')),
                ('para_birimi', models.CharField(choices=[('TRY', 'TRY'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='TRY', max_length=3, verbose_name='para birimi')),
                ('kredi_limiti', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='kredi/risk limiti')),
                ('iskonto_yuzdesi', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='varsayılan iskonto %')),
                ('notlar', models.TextField(blank=True, verbose_name='notlar')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cariler', to='core.carikategori', verbose_name='kategori')),
                ('sehir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cariler', to='core.sehir', verbose_name='şehir')),
                ('sevk_sehir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sevk_cariler', to='core.sehir', verbose_name='sevk şehir')),
                ('sevk_ulke', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sevk_cariler', to='core.ulke', verbose_name='sevk ülke')),
                ('ulke', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cariler', to='core.ulke', verbose_name='ülke')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'cari',
                'verbose_name_plural': 'cariler',
                'db_table': 'cari',
                'ordering': ['unvan'],
            },
        ),
        migrations.CreateModel(
            name='CariBanka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('banka_adi', models.CharField(max_length=100, verbose_name='banka')),
                ('hesap_sahibi', models.CharField(blank=True, max_length=200, verbose_name='hesap sahibi')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('swift', models.CharField(blank=True, max_length=15, verbose_name='SWIFT/BIC')),
                ('para_birimi', models.CharField(choices=[('TRY', 'TRY'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='TRY', max_length=3, verbose_name='para birimi')),
                ('aciklama', models.CharField(blank=True, max_length=200, verbose_name='açıklama')),
                ('varsayilan', models.BooleanField(default=False, verbose_name='varsayılan')),
                ('cari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banka_hesaplari', to='core.cari', verbose_name='cari')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'banka hesabı',
                'verbose_name_plural': 'banka hesapları',
                'db_table': 'cari_banka',
                'ordering': ['-varsayilan', 'banka_adi'],
            },
        ),
        migrations.CreateModel(
            name='CariYetkili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('ad_soyad', models.CharField(max_length=120, verbose_name='ad soyad')),
                ('unvan', models.CharField(blank=True, max_length=80, verbose_name='görev/unvan')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='telefon')),
                ('eposta', models.EmailField(blank=True, max_length=254, verbose_name='e-posta')),
                ('notlar', models.CharField(blank=True, max_length=200, verbose_name='notlar')),
                ('cari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yetkililer', to='core.cari', verbose_name='cari')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'yetkili kişi',
                'verbose_name_plural': 'yetkili kişiler',
                'db_table': 'cari_yetkili',
                'ordering': ['ad_soyad'],
            },
        ),
        migrations.AddIndex(
            model_name='cari',
            index=models.Index(fields=['unvan'], name='cari_unvan_615794_idx'),
        ),
        migrations.AddConstraint(
            model_name='cari',
            constraint=models.UniqueConstraint(condition=models.Q(('silindi', False)), fields=('kod',), name='uq_cari_kod_aktif'),
        ),
        migrations.AddConstraint(
            model_name='cari',
            constraint=models.UniqueConstraint(condition=models.Q(('silindi', False), models.Q(('vkn_tckn', ''), _negated=True)), fields=('vkn_tckn',), name='uq_cari_vkn_dolu'),
        ),
        migrations.AddConstraint(
            model_name='cari',
            constraint=models.UniqueConstraint(condition=models.Q(('silindi', False), models.Q(('tax_id', ''), _negated=True)), fields=('tax_id',), name='uq_cari_taxid_dolu'),
        ),
    ]
