# Generated by Django 6.0.5 on 2026-06-07 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_cari_caribanka_cariyetkili_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carikategori',
            name='aciklama',
        ),
    ]
