# Generated by Django 6.0.5 on 2026-06-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_carikategori_aciklama'),
    ]

    operations = [
        migrations.AddField(
            model_name='cari',
            name='muhasebe_kodu',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='muhasebe kodu'),
        ),
    ]
