# Generated by Django 6.0.5 on 2026-06-07 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_cari_muhasebe_kodu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KdvOrani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('sira', models.PositiveSmallIntegerField(default=0, verbose_name='sıra')),
                ('aciklama', models.CharField(max_length=100, verbose_name='açıklama')),
                ('oran', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='KDV oranı (%)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('hesap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kdv_oranlari', to='core.hesapplani', verbose_name='muhasebe hesabı')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'KDV oranı',
                'verbose_name_plural': 'KDV oranları',
                'db_table': 'kdv_orani',
                'ordering': ['sira', 'oran'],
                'constraints': [models.CheckConstraint(condition=models.Q(('oran__gte', 0)), name='ck_kdv_orani_gte0')],
            },
        ),
        migrations.CreateModel(
            name='TevkifatOrani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('kod', models.CharField(max_length=20, verbose_name='kod')),
                ('pay', models.PositiveSmallIntegerField(verbose_name='pay')),
                ('payda', models.PositiveSmallIntegerField(verbose_name='payda')),
                ('aciklama', models.CharField(blank=True, max_length=200, verbose_name='açıklama')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('hesap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tevkifat_oranlari', to='core.hesapplani', verbose_name='muhasebe hesabı')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'tevkifat oranı',
                'verbose_name_plural': 'tevkifat oranları',
                'db_table': 'tevkifat_orani',
                'ordering': ['kod'],
                'constraints': [models.CheckConstraint(condition=models.Q(('pay__gte', 0)), name='ck_tevkifat_pay_gte0'), models.CheckConstraint(condition=models.Q(('payda__gt', 0)), name='ck_tevkifat_payda_gt0'), models.UniqueConstraint(condition=models.Q(('silindi', False)), fields=('kod',), name='uq_tevkifat_kod_aktif')],
            },
        ),
    ]
