# Generated by Django 6.0.5 on 2026-06-07 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_hesapplani_ust_hesap_kaldir'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='yevmiyefisi',
            name='kaynak',
            field=models.CharField(choices=[('MANUEL', 'Manuel'), ('FATURA', 'Fatura (otomatik)')], default='MANUEL', max_length=20, verbose_name='kaynak'),
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('tarih', models.DateField(verbose_name='fatura tarihi')),
                ('fatura_no', models.CharField(blank=True, max_length=50, verbose_name='fatura no')),
                ('para_birimi', models.CharField(choices=[('TRY', 'TRY'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='TRY', max_length=3, verbose_name='para birimi')),
                ('kur', models.DecimalField(decimal_places=6, default=1, max_digits=18, verbose_name='kur (TL)')),
                ('cari', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faturalar', to='core.cari', verbose_name='cari')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('fis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faturalar', to='core.yevmiyefisi', verbose_name='yevmiye fişi')),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faturalar', to='core.faturatipi', verbose_name='fatura tipi')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'fatura',
                'verbose_name_plural': 'faturalar',
                'db_table': 'fatura',
                'ordering': ['-tarih', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FaturaSatir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('miktar', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='miktar')),
                ('birim_fiyat', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='birim fiyat')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satirlar', to='core.fatura', verbose_name='fatura')),
                ('kdv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fatura_satirlari', to='core.kdvorani', verbose_name='KDV oranı')),
                ('stok', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fatura_satirlari', to='core.stok', verbose_name='stok')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'fatura satırı',
                'verbose_name_plural': 'fatura satırları',
                'db_table': 'fatura_satir',
                'ordering': ['fatura', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='fatura',
            constraint=models.CheckConstraint(condition=models.Q(('kur__gt', 0)), name='ck_fatura_kur_gt0'),
        ),
        migrations.AddConstraint(
            model_name='faturasatir',
            constraint=models.CheckConstraint(condition=models.Q(('miktar__gt', 0)), name='ck_fatura_satir_miktar_gt0'),
        ),
        migrations.AddConstraint(
            model_name='faturasatir',
            constraint=models.CheckConstraint(condition=models.Q(('birim_fiyat__gte', 0)), name='ck_fatura_satir_fiyat_gte0'),
        ),
    ]
