# Generated by Django 6.0.5 on 2026-06-07 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_yevmiyefisi_kaynak_fatura_faturasatir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturasatir',
            name='tevkifat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fatura_satirlari', to='core.tevkifatorani', verbose_name='tevkifat oranı'),
        ),
    ]
