# Generated by Django 6.0.5 on 2026-06-08 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_faturasatir_tevkifat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('kod', models.CharField(max_length=20, verbose_name='kod')),
                ('ad', models.CharField(max_length=100, verbose_name='ad')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'depo',
                'verbose_name_plural': 'depolar',
                'db_table': 'depo',
                'ordering': ['kod'],
            },
        ),
        migrations.CreateModel(
            name='StokHareket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('tarih', models.DateField(verbose_name='tarih')),
                ('tur', models.CharField(choices=[('GIRIS', 'Giriş'), ('CIKIS', 'Çıkış')], max_length=5, verbose_name='tür')),
                ('miktar', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='miktar')),
                ('aciklama', models.CharField(blank=True, max_length=300, verbose_name='açıklama')),
                ('kaynak', models.CharField(choices=[('MANUEL', 'Manuel')], default='MANUEL', max_length=20, verbose_name='kaynak')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('depo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hareketler', to='core.depo', verbose_name='depo')),
                ('stok', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hareketler', to='core.stok', verbose_name='stok')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'stok hareketi',
                'verbose_name_plural': 'stok hareketleri',
                'db_table': 'stok_hareket',
                'ordering': ['-tarih', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='depo',
            constraint=models.UniqueConstraint(condition=models.Q(('silindi', False)), fields=('kod',), name='uq_depo_kod_aktif'),
        ),
        migrations.AddConstraint(
            model_name='depo',
            constraint=models.UniqueConstraint(condition=models.Q(('silindi', False)), fields=('ad',), name='uq_depo_ad_aktif'),
        ),
        migrations.AddIndex(
            model_name='stokhareket',
            index=models.Index(fields=['stok', 'depo'], name='idx_stokhareket_stok_depo'),
        ),
        migrations.AddConstraint(
            model_name='stokhareket',
            constraint=models.CheckConstraint(condition=models.Q(('miktar__gt', 0)), name='ck_stok_hareket_miktar_gt0'),
        ),
    ]
