# Generated by Django 6.0.5 on 2026-06-15 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_depo_stokhareket_depo_uq_depo_kod_aktif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='depo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faturalar', to='core.depo', verbose_name='depo'),
        ),
        migrations.AddField(
            model_name='stokhareket',
            name='fatura_satir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stok_hareketleri', to='core.faturasatir', verbose_name='kaynak fatura satırı'),
        ),
        migrations.AlterField(
            model_name='stokhareket',
            name='kaynak',
            field=models.CharField(choices=[('MANUEL', 'Manuel'), ('FATURA', 'Fatura')], default='MANUEL', max_length=20, verbose_name='kaynak'),
        ),
    ]
