# Generated by Django 6.0.5 on 2026-06-17 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_kasa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('ad', models.CharField(max_length=100, verbose_name='hesap adı')),
                ('banka_adi', models.CharField(blank=True, max_length=150, verbose_name='banka adı')),
                ('sube', models.CharField(blank=True, max_length=100, verbose_name='şube')),
                ('hesap_no', models.CharField(blank=True, max_length=40, verbose_name='hesap no')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('para_birimi', models.CharField(choices=[('TRY', 'TRY'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='TRY', max_length=3, verbose_name='para birimi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('muhasebe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='banka_hesaplari', to='core.hesapplani', verbose_name='muhasebe hesabı')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'banka hesabı',
                'verbose_name_plural': 'banka hesapları',
                'db_table': 'finans_banka',
                'ordering': ['ad'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('silindi', False)), fields=('ad',), name='uq_banka_ad_aktif')],
            },
        ),
        migrations.CreateModel(
            name='CekSenet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('tip', models.CharField(choices=[('CEK', 'Çek'), ('SENET', 'Senet')], max_length=5, verbose_name='tip')),
                ('yon', models.CharField(choices=[('ALINAN', 'Alınan'), ('VERILEN', 'Verilen')], max_length=7, verbose_name='yön')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='tutar')),
                ('para_birimi', models.CharField(choices=[('TRY', 'TRY'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='TRY', max_length=3, verbose_name='para birimi')),
                ('vade', models.DateField(verbose_name='vade tarihi')),
                ('kesideci', models.CharField(blank=True, max_length=200, verbose_name='keşideci')),
                ('belge_no', models.CharField(blank=True, max_length=50, verbose_name='belge no')),
                ('durum', models.CharField(choices=[('PORTFOYDE', 'Portföyde'), ('TAHSIL', 'Tahsil Edildi'), ('ODENDI', 'Ödendi'), ('CIRO', 'Ciro Edildi'), ('IADE', 'İade'), ('KARSILIKSIZ', 'Karşılıksız')], default='PORTFOYDE', max_length=12, verbose_name='durum')),
                ('cari', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cek_senetler', to='core.cari', verbose_name='cari')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('muhasebe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cek_senetler', to='core.hesapplani', verbose_name='muhasebe hesabı')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'çek/senet',
                'verbose_name_plural': 'çek/senetler',
                'db_table': 'finans_cek_senet',
                'ordering': ['vade', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('tutar__gt', 0)), name='ck_cek_senet_tutar_gt0')],
            },
        ),
        migrations.CreateModel(
            name='Kredi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('ad', models.CharField(max_length=100, verbose_name='kredi adı')),
                ('banka_adi', models.CharField(blank=True, max_length=150, verbose_name='banka adı')),
                ('anapara', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='anapara')),
                ('faiz_orani', models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='aylık faiz oranı (%)')),
                ('para_birimi', models.CharField(choices=[('TRY', 'TRY'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='TRY', max_length=3, verbose_name='para birimi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('muhasebe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='krediler', to='core.hesapplani', verbose_name='muhasebe hesabı')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'kredi',
                'verbose_name_plural': 'krediler',
                'db_table': 'finans_kredi',
                'ordering': ['ad'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('silindi', False)), fields=('ad',), name='uq_kredi_ad_aktif'), models.CheckConstraint(condition=models.Q(('anapara__gte', 0)), name='ck_kredi_anapara_gte0'), models.CheckConstraint(condition=models.Q(('faiz_orani__gte', 0)), name='ck_kredi_faiz_gte0')],
            },
        ),
        migrations.CreateModel(
            name='KrediKarti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('ad', models.CharField(max_length=100, verbose_name='kart adı')),
                ('banka_adi', models.CharField(blank=True, max_length=150, verbose_name='banka adı')),
                ('kart_son4', models.CharField(blank=True, max_length=4, verbose_name='kart no (son 4)')),
                ('limit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='kart limiti')),
                ('kesim_gunu', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='hesap kesim günü')),
                ('son_odeme_gunu', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='son ödeme günü')),
                ('para_birimi', models.CharField(choices=[('TRY', 'TRY'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='TRY', max_length=3, verbose_name='para birimi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('muhasebe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kredi_kartlari', to='core.hesapplani', verbose_name='muhasebe hesabı')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'kredi kartı',
                'verbose_name_plural': 'kredi kartları',
                'db_table': 'finans_kredi_karti',
                'ordering': ['ad'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('silindi', False)), fields=('ad',), name='uq_kredi_karti_ad_aktif'), models.CheckConstraint(condition=models.Q(('limit__gte', 0)), name='ck_kredi_karti_limit_gte0')],
            },
        ),
    ]
