# Generated by Django 6.0.5 on 2026-06-17 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_banka_ceksenet_kredi_kredikarti'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banka',
            options={'ordering': ['ad'], 'verbose_name': 'banka', 'verbose_name_plural': 'bankalar'},
        ),
        migrations.RemoveField(
            model_name='banka',
            name='banka_adi',
        ),
        migrations.RemoveField(
            model_name='banka',
            name='hesap_no',
        ),
        migrations.RemoveField(
            model_name='banka',
            name='iban',
        ),
        migrations.RemoveField(
            model_name='banka',
            name='muhasebe',
        ),
        migrations.RemoveField(
            model_name='banka',
            name='para_birimi',
        ),
        migrations.AddField(
            model_name='banka',
            name='adres',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='adres'),
        ),
        migrations.AddField(
            model_name='banka',
            name='kisa_ad',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='kısa ad'),
        ),
        migrations.AddField(
            model_name='banka',
            name='swift_kod',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='SWIFT/BIC'),
        ),
        migrations.AlterField(
            model_name='banka',
            name='ad',
            field=models.CharField(max_length=150, verbose_name='banka adı'),
        ),
        migrations.AlterField(
            model_name='banka',
            name='sube',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='şube'),
        ),
        migrations.CreateModel(
            name='BankaHesap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('ad', models.CharField(max_length=100, verbose_name='hesap adı')),
                ('hesap_no', models.CharField(blank=True, max_length=40, verbose_name='hesap no')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('para_birimi', models.CharField(choices=[('TRY', 'TRY'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='TRY', max_length=3, verbose_name='para birimi')),
                ('banka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hesaplar', to='core.banka', verbose_name='banka')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('muhasebe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='banka_hesaplari', to='core.hesapplani', verbose_name='muhasebe hesabı')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'banka hesabı',
                'verbose_name_plural': 'banka hesapları',
                'db_table': 'finans_banka_hesap',
                'ordering': ['banka', 'ad'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('silindi', False)), fields=('banka', 'ad'), name='uq_banka_hesap_ad_aktif')],
            },
        ),
    ]
