# Generated by Django 6.0.5 on 2026-06-26 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_banka_options_remove_banka_banka_adi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yevmiyefisi',
            name='kasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fisler', to='core.kasa', verbose_name='kaynak kasa'),
        ),
        migrations.AlterField(
            model_name='yevmiyefisi',
            name='kaynak',
            field=models.CharField(choices=[('MANUEL', 'Manuel'), ('FATURA', 'Fatura (otomatik)'), ('KASA', 'Kasa Hareketi (otomatik)')], default='MANUEL', max_length=20, verbose_name='kaynak'),
        ),
    ]
