# Generated by Django 6.0.5 on 2026-06-27 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_yevmiyefisi_kasa_alter_yevmiyefisi_kaynak'),
    ]

    operations = [
        migrations.AddField(
            model_name='yevmiyefisi',
            name='banka_hesap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fisler', to='core.bankahesap', verbose_name='kaynak banka hesabı'),
        ),
        migrations.AlterField(
            model_name='yevmiyefisi',
            name='kaynak',
            field=models.CharField(choices=[('MANUEL', 'Manuel'), ('FATURA', 'Fatura (otomatik)'), ('KASA', 'Kasa Hareketi (otomatik)'), ('BANKA', 'Banka Hareketi (otomatik)')], default='MANUEL', max_length=20, verbose_name='kaynak'),
        ),
    ]
