# Generated by Django 6.0.5 on 2026-06-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_yevmiyefisi_banka_hesap_alter_yevmiyefisi_kaynak'),
    ]

    operations = [
        migrations.AddField(
            model_name='banka',
            name='musteri_no',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='müşteri no'),
        ),
    ]
