# Generated by Django 6.0.5 on 2026-06-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_banka_musteri_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='banka',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='banka_logo/', verbose_name='logo'),
        ),
    ]
