# Generated by Django 6.0.5 on 2026-06-28 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_banka_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='yevmiyefisi',
            name='cek_senet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fisler', to='core.ceksenet', verbose_name='kaynak çek/senet'),
        ),
        migrations.AlterField(
            model_name='yevmiyefisi',
            name='kaynak',
            field=models.CharField(choices=[('MANUEL', 'Manuel'), ('FATURA', 'Fatura (otomatik)'), ('KASA', 'Kasa Hareketi (otomatik)'), ('BANKA', 'Banka Hareketi (otomatik)'), ('CEK_SENET', 'Çek/Senet (otomatik)')], default='MANUEL', max_length=20, verbose_name='kaynak'),
        ),
    ]
