# Generated by Django 6.0.5 on 2026-06-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_yevmiyefisi_cek_senet_alter_yevmiyefisi_kaynak'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ceksenet',
            name='ck_cek_senet_tutar_gt0',
        ),
        migrations.RemoveField(
            model_name='yevmiyefisi',
            name='cek_senet',
        ),
        migrations.AlterField(
            model_name='yevmiyefisi',
            name='kaynak',
            field=models.CharField(choices=[('MANUEL', 'Manuel'), ('FATURA', 'Fatura (otomatik)'), ('KASA', 'Kasa Hareketi (otomatik)'), ('BANKA', 'Banka Hareketi (otomatik)')], default='MANUEL', max_length=20, verbose_name='kaynak'),
        ),
        migrations.DeleteModel(
            name='CekSenet',
        ),
    ]
