# Generated by Django 6.0.5 on 2026-06-28 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_remove_ceksenet_ck_cek_senet_tutar_gt0_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CekHesapAyari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('portfoy_cek', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.hesapplani', verbose_name='portföydeki çek hesabı')),
                ('portfoy_senet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.hesapplani', verbose_name='portföydeki senet hesabı')),
                ('tahsilde_cek', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.hesapplani', verbose_name='bankada tahsildeki çek hesabı')),
                ('tahsilde_senet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.hesapplani', verbose_name='bankada tahsildeki senet hesabı')),
                ('teminatta_cek', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.hesapplani', verbose_name='bankada teminattaki çek hesabı')),
                ('teminatta_senet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.hesapplani', verbose_name='bankada teminattaki senet hesabı')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
                ('verilen_cek', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.hesapplani', verbose_name='verilen çek hesabı')),
                ('verilen_senet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.hesapplani', verbose_name='verilen senet hesabı')),
            ],
            options={
                'verbose_name': 'çek/senet hesap ayarı',
                'verbose_name_plural': 'çek/senet hesap ayarı',
                'db_table': 'finans_cek_hesap_ayari',
            },
        ),
    ]
