# Generated by Django 6.0.5 on 2026-06-28 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_cekhesapayari'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='yevmiyefisi',
            name='kaynak',
            field=models.CharField(choices=[('MANUEL', 'Manuel'), ('FATURA', 'Fatura (otomatik)'), ('KASA', 'Kasa Hareketi (otomatik)'), ('BANKA', 'Banka Hareketi (otomatik)'), ('CEK_SENET', 'Çek/Senet Bordrosu (otomatik)')], default='MANUEL', max_length=20, verbose_name='kaynak'),
        ),
        migrations.CreateModel(
            name='CekBordrosu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('tur', models.CharField(choices=[('CARI_GIRIS', 'Cari Giriş'), ('FIRMA_CIKIS', 'Firma Çek-Senet'), ('CARI_CIRO', 'Cari Ciro'), ('BANKA_TAHSIL', 'Banka Tahsil'), ('BANKA_TEMINAT', 'Banka Teminat'), ('CARI_IADE', 'Cari İade'), ('BANKA_TAHSIL_IADE', 'Banka Tahsil İade'), ('BANKA_TEMINAT_IADE', 'Banka Teminat İade')], max_length=20, verbose_name='tür')),
                ('tarih', models.DateField(verbose_name='işlem tarihi')),
                ('aciklama', models.CharField(blank=True, max_length=300, verbose_name='açıklama')),
                ('banka_hesap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cek_bordrolari', to='core.bankahesap', verbose_name='banka hesabı')),
                ('cari', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cek_bordrolari', to='core.cari', verbose_name='cari')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'çek/senet bordrosu',
                'verbose_name_plural': 'çek/senet bordroları',
                'db_table': 'finans_cek_bordrosu',
                'ordering': ['-tarih', '-id'],
            },
        ),
        migrations.AddField(
            model_name='yevmiyefisi',
            name='cek_bordrosu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fisler', to='core.cekbordrosu', verbose_name='kaynak çek/senet bordrosu'),
        ),
        migrations.CreateModel(
            name='CekSenet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('tip', models.CharField(choices=[('CEK', 'Çek'), ('SENET', 'Senet')], max_length=5, verbose_name='tip')),
                ('yon', models.CharField(choices=[('ALINAN', 'Alınan'), ('VERILEN', 'Verilen')], max_length=7, verbose_name='yön')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='tutar')),
                ('para_birimi', models.CharField(choices=[('TRY', 'TRY'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='TRY', max_length=3, verbose_name='para birimi')),
                ('vade', models.DateField(verbose_name='vade tarihi')),
                ('kesideci', models.CharField(blank=True, max_length=200, verbose_name='keşideci')),
                ('belge_no', models.CharField(blank=True, max_length=50, verbose_name='belge no')),
                ('durum', models.CharField(choices=[('PORTFOYDE', 'Portföyde'), ('TAHSILDE', 'Bankada Tahsilde'), ('TEMINATTA', 'Bankada Teminatta'), ('CIRO', 'Ciro Edildi'), ('IADE', 'İade Edildi'), ('TAHSIL', 'Tahsil Edildi'), ('VERILDI', 'Verildi'), ('ODENDI', 'Ödendi'), ('KARSILIKSIZ', 'Karşılıksız')], default='PORTFOYDE', max_length=12, verbose_name='durum')),
                ('cari', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cek_senetler', to='core.cari', verbose_name='cari')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('giris_bordrosu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cek_senetler', to='core.cekbordrosu', verbose_name='giriş bordrosu')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'çek/senet',
                'verbose_name_plural': 'çek/senetler',
                'db_table': 'finans_cek_senet',
                'ordering': ['vade', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('tutar__gt', 0)), name='ck_cek_senet_tutar_gt0')],
            },
        ),
    ]
