# Generated by Django 6.0.5 on 2026-06-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_yevmiyefisi_kaynak_cekbordrosu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceksenet',
            name='arka_yuz',
            field=models.ImageField(blank=True, null=True, upload_to='cek_senet/', verbose_name='arka yüz görseli'),
        ),
        migrations.AddField(
            model_name='ceksenet',
            name='on_yuz',
            field=models.ImageField(blank=True, null=True, upload_to='cek_senet/', verbose_name='ön yüz görseli'),
        ),
    ]
