# Generated by Django 6.0.5 on 2026-06-28 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_ceksenet_arka_yuz_ceksenet_on_yuz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CekBordroSatir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('onceki_durum', models.CharField(choices=[('PORTFOYDE', 'Portföyde'), ('TAHSILDE', 'Bankada Tahsilde'), ('TEMINATTA', 'Bankada Teminatta'), ('CIRO', 'Ciro Edildi'), ('IADE', 'İade Edildi'), ('TAHSIL', 'Tahsil Edildi'), ('VERILDI', 'Verildi'), ('ODENDI', 'Ödendi'), ('KARSILIKSIZ', 'Karşılıksız')], max_length=12, verbose_name='önceki durum')),
                ('bordro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='satirlar', to='core.cekbordrosu', verbose_name='bordro')),
                ('cek_senet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bordro_satirlari', to='core.ceksenet', verbose_name='çek/senet')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'çek/senet bordro satırı',
                'verbose_name_plural': 'çek/senet bordro satırları',
                'db_table': 'finans_cek_bordro_satir',
                'ordering': ['id'],
            },
        ),
    ]
