# Generated by Django 6.0.5 on 2026-07-11 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_cekbordrosatir'),
    ]

    operations = [
        migrations.AddField(
            model_name='cekbordrosu',
            name='kasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cek_bordrolari', to='core.kasa', verbose_name='kasa'),
        ),
        migrations.AlterField(
            model_name='cekbordrosu',
            name='tur',
            field=models.CharField(choices=[('CARI_GIRIS', 'Cari Giriş'), ('FIRMA_CIKIS', 'Firma Çek-Senet'), ('CARI_CIRO', 'Cari Ciro'), ('BANKA_TAHSIL', 'Banka Tahsil'), ('BANKA_TEMINAT', 'Banka Teminat'), ('CARI_IADE', 'Cari İade'), ('BANKA_TAHSIL_IADE', 'Banka Tahsil İade'), ('BANKA_TEMINAT_IADE', 'Banka Teminat İade'), ('TAHSIL', 'Tahsil Gerçekleşme')], max_length=20, verbose_name='tür'),
        ),
    ]
