# Generated by Django 6.0.5 on 2026-07-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_cekbordrosu_tur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cekbordrosu',
            name='tur',
            field=models.CharField(choices=[('CARI_GIRIS', 'Cari Giriş'), ('FIRMA_CIKIS', 'Firma Çek-Senet'), ('CARI_CIRO', 'Cari Ciro'), ('BANKA_TAHSIL', 'Banka Tahsil'), ('BANKA_TEMINAT', 'Banka Teminat'), ('CARI_IADE', 'Cari İade'), ('BANKA_TAHSIL_IADE', 'Banka Tahsil İade'), ('BANKA_TEMINAT_IADE', 'Banka Teminat İade'), ('TAHSIL', 'Tahsil Gerçekleşme'), ('ODEME', 'Firma Çek Ödeme'), ('KARSILIKSIZ', 'Karşılıksız'), ('FIRMA_KARSILIKSIZ', 'Firma Çek Karşılıksız')], max_length=20, verbose_name='tür'),
        ),
    ]
