# Generated by Django 6.0.5 on 2026-07-18 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_cekbordrosu_tur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kredikarti',
            name='banka_adi',
        ),
        migrations.AddField(
            model_name='kredikarti',
            name='banka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kredi_kartlari', to='core.banka', verbose_name='banka'),
        ),
    ]
