# Generated by Django 6.0.5 on 2026-07-18 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_remove_kredikarti_banka_adi_kredikarti_banka'),
    ]

    operations = [
        migrations.AddField(
            model_name='yevmiyefisi',
            name='kredi_karti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fisler', to='core.kredikarti', verbose_name='kaynak kredi kartı'),
        ),
        migrations.AlterField(
            model_name='yevmiyefisi',
            name='kaynak',
            field=models.CharField(choices=[('MANUEL', 'Manuel'), ('FATURA', 'Fatura (otomatik)'), ('KASA', 'Kasa Hareketi (otomatik)'), ('BANKA', 'Banka Hareketi (otomatik)'), ('CEK_SENET', 'Çek/Senet Bordrosu (otomatik)'), ('KREDI_KARTI', 'Kredi Kartı Hareketi (otomatik)')], default='MANUEL', max_length=20, verbose_name='kaynak'),
        ),
    ]
