# Generated by Django 6.0.5 on 2026-07-18 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_yevmiyefisi_kredi_karti_alter_yevmiyefisi_kaynak'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KrediKartiTaksit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('taksit_adedi', models.PositiveSmallIntegerField(verbose_name='taksit adedi')),
                ('ilk_vade', models.DateField(verbose_name='ilk taksit tarihi')),
                ('toplam_tutar', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='toplam tutar')),
                ('para_birimi', models.CharField(choices=[('TRY', 'TRY'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='TRY', max_length=3, verbose_name='para birimi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('fis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taksit_planlari', to='core.yevmiyefisi', verbose_name='harcama fişi')),
                ('kart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taksit_planlari', to='core.kredikarti', verbose_name='kredi kartı')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'kredi kartı taksit planı',
                'verbose_name_plural': 'kredi kartı taksit planları',
                'db_table': 'finans_kredi_karti_taksit',
                'ordering': ['ilk_vade', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('taksit_adedi__gte', 2)), name='ck_kk_taksit_adedi_gte2')],
            },
        ),
    ]
