# Generated by Django 6.0.5 on 2026-07-18 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_kredikartitaksit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kredi',
            name='banka_adi',
        ),
        migrations.AddField(
            model_name='kredi',
            name='banka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='krediler', to='core.banka', verbose_name='banka'),
        ),
        migrations.AddField(
            model_name='yevmiyefisi',
            name='kredi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fisler', to='core.kredi', verbose_name='kaynak kredi'),
        ),
        migrations.AlterField(
            model_name='yevmiyefisi',
            name='kaynak',
            field=models.CharField(choices=[('MANUEL', 'Manuel'), ('FATURA', 'Fatura (otomatik)'), ('KASA', 'Kasa Hareketi (otomatik)'), ('BANKA', 'Banka Hareketi (otomatik)'), ('CEK_SENET', 'Çek/Senet Bordrosu (otomatik)'), ('KREDI_KARTI', 'Kredi Kartı Hareketi (otomatik)'), ('KREDI', 'Kredi Hareketi (otomatik)')], default='MANUEL', max_length=20, verbose_name='kaynak'),
        ),
    ]
