# Generated by Django 6.0.5 on 2026-07-18 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_remove_kredi_banka_adi_kredi_banka_yevmiyefisi_kredi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KrediTaksit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('sira', models.PositiveSmallIntegerField(verbose_name='sıra')),
                ('vade', models.DateField(verbose_name='vade')),
                ('anapara', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='anapara')),
                ('faiz', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='faiz')),
                ('durum', models.CharField(choices=[('BEKLIYOR', 'Bekliyor'), ('ODENDI', 'Ödendi')], default='BEKLIYOR', max_length=10, verbose_name='durum')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('kredi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taksitler', to='core.kredi', verbose_name='kredi')),
                ('odeme_fisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='odenen_taksitler', to='core.yevmiyefisi', verbose_name='ödeme fişi')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'kredi taksiti',
                'verbose_name_plural': 'kredi taksitleri',
                'db_table': 'finans_kredi_taksit',
                'ordering': ['kredi_id', 'sira', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('anapara__gt', 0)), name='ck_kredi_taksit_anapara_gt0'), models.CheckConstraint(condition=models.Q(('faiz__gte', 0)), name='ck_kredi_taksit_faiz_gte0')],
            },
        ),
    ]
