# Generated by Django 6.0.5 on 2026-07-18 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_kreditaksit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeklifSiparis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('belge_tur', models.CharField(choices=[('TEKLIF', 'Teklif'), ('SIPARIS', 'Sipariş')], max_length=7, verbose_name='belge türü')),
                ('yon', models.CharField(choices=[('ALIS', 'Alış'), ('SATIS', 'Satış')], max_length=5, verbose_name='yön')),
                ('tarih', models.DateField(verbose_name='belge tarihi')),
                ('gecerlilik_teslim_tarihi', models.DateField(blank=True, null=True, verbose_name='geçerlilik / teslim tarihi')),
                ('belge_no', models.CharField(blank=True, max_length=50, verbose_name='belge no')),
                ('para_birimi', models.CharField(choices=[('TRY', 'TRY'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='TRY', max_length=3, verbose_name='para birimi')),
                ('aciklama', models.CharField(blank=True, max_length=500, verbose_name='açıklama')),
                ('cari', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teklif_siparisler', to='core.cari', verbose_name='cari')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'teklif / sipariş',
                'verbose_name_plural': 'teklif / siparişler',
                'db_table': 'teklif_siparis',
                'ordering': ['-tarih', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TeklifSiparisKalem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('miktar', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='miktar')),
                ('birim_fiyat', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='birim fiyat')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('kdv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teklif_siparis_kalemleri', to='core.kdvorani', verbose_name='KDV oranı')),
                ('stok', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teklif_siparis_kalemleri', to='core.stok', verbose_name='stok')),
                ('teklif_siparis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalemler', to='core.teklifsiparis', verbose_name='teklif / sipariş')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'teklif / sipariş kalemi',
                'verbose_name_plural': 'teklif / sipariş kalemleri',
                'db_table': 'teklif_siparis_kalem',
                'ordering': ['teklif_siparis', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('miktar__gt', 0)), name='ck_ts_kalem_miktar_gt0'), models.CheckConstraint(condition=models.Q(('birim_fiyat__gte', 0)), name='ck_ts_kalem_fiyat_gte0')],
            },
        ),
    ]
