# Generated by Django 6.0.5 on 2026-07-18 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_teklifsiparis_teklifsipariskalem'),
    ]

    operations = [
        migrations.AddField(
            model_name='teklifsiparis',
            name='kaynak_teklif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donusen_siparisler', to='core.teklifsiparis', verbose_name='kaynak teklif'),
        ),
    ]
