# Generated by Django 6.0.5 on 2026-07-18 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_teklifsiparis_kaynak_teklif'),
    ]

    operations = [
        migrations.AddField(
            model_name='teklifsiparis',
            name='fatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kaynak_siparisler', to='core.fatura', verbose_name='fatura'),
        ),
    ]
