# Generated by Django 6.0.5 on 2026-07-18 22:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_teklifsiparis_fatura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teklifsiparis',
            name='durum',
            field=models.CharField(choices=[('TASLAK', 'Taslak'), ('ONAYLI', 'Onaylı')], default='TASLAK', max_length=6, verbose_name='durum'),
        ),
        migrations.AddField(
            model_name='teklifsiparis',
            name='sira',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='sıra'),
        ),
        migrations.AddField(
            model_name='teklifsiparis',
            name='yil',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='yıl'),
        ),
        migrations.AlterField(
            model_name='teklifsiparis',
            name='belge_no',
            field=models.CharField(blank=True, editable=False, max_length=50, verbose_name='belge no'),
        ),
        migrations.AddConstraint(
            model_name='teklifsiparis',
            constraint=models.UniqueConstraint(condition=models.Q(('sira__isnull', False)), fields=('belge_tur', 'yon', 'yil', 'sira'), name='uq_teklif_siparis_tur_yon_yil_sira'),
        ),
    ]
