# Generated by Django 6.0.5 on 2026-08-30 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_teklifsiparis_durum_teklifsiparis_sira_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teklifsipariskalem',
            name='tevkifat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teklif_siparis_kalemleri', to='core.tevkifatorani', verbose_name='tevkifat oranı'),
        ),
    ]
