# Generated by Django 6.0.5 on 2026-08-30 18:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_teklifsipariskalem_tevkifat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stok',
            name='alis_fiyati',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='alış fiyatı'),
        ),
        migrations.AddField(
            model_name='stok',
            name='alis_fiyati_pb',
            field=models.CharField(choices=[('TRY', 'TRY'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='TRY', max_length=3, verbose_name='alış fiyatı para birimi'),
        ),
        migrations.AddConstraint(
            model_name='stok',
            constraint=models.CheckConstraint(condition=models.Q(('alis_fiyati__isnull', True), ('alis_fiyati__gte', 0), _connector='OR'), name='ck_stok_alis_fiyati_gte0'),
        ),
    ]
