# Generated by Django 6.0.5 on 2026-08-30 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_stok_alis_fiyati_stok_alis_fiyati_pb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='durum',
            field=models.CharField(choices=[('TASLAK', 'Taslak'), ('ONAYLI', 'Onaylı')], default='TASLAK', max_length=6, verbose_name='durum'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='yon',
            field=models.CharField(blank=True, choices=[('SATIS', 'Satış'), ('ALIS', 'Alış')], max_length=5, null=True, verbose_name='yön'),
        ),
        migrations.AddField(
            model_name='stokhareket',
            name='teklif_siparis_kalem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stok_hareketleri', to='core.teklifsipariskalem', verbose_name='kaynak irsaliye kalemi'),
        ),
        migrations.AddField(
            model_name='teklifsiparis',
            name='depo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teklif_siparisler', to='core.depo', verbose_name='depo'),
        ),
        migrations.AddField(
            model_name='teklifsiparis',
            name='kaynak_siparis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donusen_irsaliyeler', to='core.teklifsiparis', verbose_name='kaynak sipariş'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='tip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faturalar', to='core.faturatipi', verbose_name='fatura tipi'),
        ),
        migrations.AlterField(
            model_name='stokhareket',
            name='kaynak',
            field=models.CharField(choices=[('MANUEL', 'Manuel'), ('FATURA', 'Fatura'), ('IRSALIYE', 'İrsaliye')], default='MANUEL', max_length=20, verbose_name='kaynak'),
        ),
        migrations.AlterField(
            model_name='teklifsiparis',
            name='belge_tur',
            field=models.CharField(choices=[('TEKLIF', 'Teklif'), ('SIPARIS', 'Sipariş'), ('IRSALIYE', 'İrsaliye')], max_length=8, verbose_name='belge türü'),
        ),
    ]
