# Generated by Django 6.0.5 on 2026-08-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_fatura_yon_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='teklifsiparis',
            name='irsaliye_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='irsaliye no'),
        ),
    ]
