# Generated by Django 6.0.5 on 2026-08-31 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_teklifsiparis_irsaliye_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ekranyetki',
            name='uq_ekran_yetki',
        ),
        migrations.AddConstraint(
            model_name='ekranyetki',
            constraint=models.UniqueConstraint(condition=models.Q(('silindi', False)), fields=('kullanici', 'ekran_kod'), name='uq_ekran_yetki'),
        ),
        migrations.AddConstraint(
            model_name='kredikartitaksit',
            constraint=models.CheckConstraint(condition=models.Q(('toplam_tutar__gt', 0)), name='ck_kk_taksit_toplam_gt0'),
        ),
    ]
