# Generated by Django 6.0.5 on 2026-09-03 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_cari_aktivite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cari',
            name='sevk_adres',
        ),
        migrations.RemoveField(
            model_name='cari',
            name='sevk_farkli',
        ),
        migrations.RemoveField(
            model_name='cari',
            name='sevk_posta_kodu',
        ),
        migrations.RemoveField(
            model_name='cari',
            name='sevk_sehir',
        ),
        migrations.RemoveField(
            model_name='cari',
            name='sevk_ulke',
        ),
        migrations.CreateModel(
            name='CariSevkAdresi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('ad', models.CharField(max_length=100, verbose_name='adres adı')),
                ('adres', models.TextField(blank=True, verbose_name='adres')),
                ('posta_kodu', models.CharField(blank=True, max_length=15, verbose_name='posta kodu')),
                ('varsayilan', models.BooleanField(default=False, verbose_name='varsayılan')),
                ('cari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sevk_adresleri', to='core.cari', verbose_name='cari')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('sehir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sevk_adresleri', to='core.sehir', verbose_name='şehir')),
                ('ulke', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sevk_adresleri', to='core.ulke', verbose_name='ülke')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'sevk adresi',
                'verbose_name_plural': 'sevk adresleri',
                'db_table': 'cari_sevk_adresi',
                'ordering': ['-varsayilan', 'ad'],
            },
        ),
    ]
