# Generated by Django 6.0.5 on 2026-09-03 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_cari_sevk_adresi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carisevkadresi',
            name='posta_kodu',
        ),
    ]
