# Generated by Django 6.0.5 on 2026-09-03 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_cari_sevk_adresi_posta_kodu_kaldir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cari',
            name='posta_kodu',
        ),
    ]
