# Generated by Django 6.0.5 on 2026-09-07 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_cari_posta_kodu_kaldir'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YemekSayimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('tarih', models.DateField(verbose_name='tarih')),
                ('kisi_sayisi', models.PositiveIntegerField(verbose_name='kişi sayısı')),
                ('birim_fiyat', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='kişi başı ücret')),
                ('notlar', models.CharField(blank=True, max_length=200, verbose_name='notlar')),
                ('cari', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='yemek_sayimlari', to='core.cari', verbose_name='cari (yemek firması)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'yemek sayımı',
                'verbose_name_plural': 'yemek sayımları',
                'db_table': 'yemek_sayimi',
                'ordering': ['-tarih'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('silindi', False)), fields=('cari', 'tarih'), name='uq_yemek_sayimi_cari_tarih_aktif'), models.CheckConstraint(condition=models.Q(('birim_fiyat__gte', 0)), name='ck_yemek_sayimi_birim_fiyat_gte0')],
            },
        ),
    ]
