# Generated by Django 6.0.5 on 2026-09-07 11:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_yemek_sayimi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stok',
            name='acik_derinlik',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='açık derinlik (cm)'),
        ),
        migrations.AddField(
            model_name='stok',
            name='agirlik',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='ağırlık (kg)'),
        ),
        migrations.AddField(
            model_name='stok',
            name='azami_yuk',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='azami yük (kg)'),
        ),
        migrations.AddField(
            model_name='stok',
            name='basamak_sayisi',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='basamak sayısı'),
        ),
        migrations.AddField(
            model_name='stok',
            name='cbm',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='CBM (m³/adet)'),
        ),
        migrations.AddField(
            model_name='stok',
            name='kapali_boy',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='kapalı boy (cm)'),
        ),
        migrations.AddField(
            model_name='stok',
            name='satinalma_urunu',
            field=models.BooleanField(default=False, verbose_name='satınalma ürünü'),
        ),
        migrations.AddField(
            model_name='stok',
            name='satis_urunu',
            field=models.BooleanField(default=False, verbose_name='satış ürünü'),
        ),
        migrations.AddField(
            model_name='stok',
            name='taban_genisligi',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='taban genişliği (cm)'),
        ),
        migrations.AddField(
            model_name='stok',
            name='uretim_urunu',
            field=models.BooleanField(default=True, verbose_name='üretim ürünü'),
        ),
        migrations.AddField(
            model_name='stok',
            name='yukleme_20dc',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="20' DC yükleme adedi"),
        ),
        migrations.AddField(
            model_name='stok',
            name='yukleme_40hq',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="40' HQ yükleme adedi"),
        ),
        migrations.AddField(
            model_name='stok',
            name='yukleme_tir',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='TIR yükleme adedi'),
        ),
        migrations.AddField(
            model_name='stok',
            name='yukseklik',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='yükseklik (cm)'),
        ),
        migrations.AddConstraint(
            model_name='stok',
            constraint=models.CheckConstraint(condition=models.Q(('yukseklik__isnull', True), ('yukseklik__gte', 0), _connector='OR'), name='ck_stok_yukseklik_gte0'),
        ),
        migrations.AddConstraint(
            model_name='stok',
            constraint=models.CheckConstraint(condition=models.Q(('acik_derinlik__isnull', True), ('acik_derinlik__gte', 0), _connector='OR'), name='ck_stok_acik_derinlik_gte0'),
        ),
        migrations.AddConstraint(
            model_name='stok',
            constraint=models.CheckConstraint(condition=models.Q(('taban_genisligi__isnull', True), ('taban_genisligi__gte', 0), _connector='OR'), name='ck_stok_taban_genisligi_gte0'),
        ),
        migrations.AddConstraint(
            model_name='stok',
            constraint=models.CheckConstraint(condition=models.Q(('kapali_boy__isnull', True), ('kapali_boy__gte', 0), _connector='OR'), name='ck_stok_kapali_boy_gte0'),
        ),
        migrations.AddConstraint(
            model_name='stok',
            constraint=models.CheckConstraint(condition=models.Q(('agirlik__isnull', True), ('agirlik__gte', 0), _connector='OR'), name='ck_stok_agirlik_gte0'),
        ),
        migrations.AddConstraint(
            model_name='stok',
            constraint=models.CheckConstraint(condition=models.Q(('azami_yuk__isnull', True), ('azami_yuk__gte', 0), _connector='OR'), name='ck_stok_azami_yuk_gte0'),
        ),
        migrations.AddConstraint(
            model_name='stok',
            constraint=models.CheckConstraint(condition=models.Q(('cbm__isnull', True), ('cbm__gte', 0), _connector='OR'), name='ck_stok_cbm_gte0'),
        ),
    ]
