# Generated by Django 6.0.5 on 2026-09-07 11:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_stok_grup_backfill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stok',
            constraint=models.CheckConstraint(condition=models.Q(('satinalma_urunu', True), ('uretim_urunu', True), ('satis_urunu', True), _connector='OR'), name='ck_stok_en_az_bir_grup'),
        ),
    ]
