# Generated by Django 6.0.5 on 2026-09-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_stok_grup_zorunlu'),
    ]

    operations = [
        migrations.AddField(
            model_name='stok',
            name='gorsel',
            field=models.ImageField(blank=True, null=True, upload_to='stok_gorsel/', verbose_name='ürün görseli'),
        ),
    ]
