# Generated by Django 6.0.5 on 2026-09-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_stok_gorsel'),
    ]

    operations = [
        migrations.AddField(
            model_name='stok',
            name='model_kodu',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='model kodu'),
        ),
    ]
