# Generated by Django 6.0.5 on 2026-09-07 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_stok_model_kodu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StokFiyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('para_birimi', models.CharField(choices=[('TRY', 'TRY'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], max_length=3, verbose_name='para birimi')),
                ('fiyat', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='satış fiyatı')),
            ],
            options={
                'verbose_name': 'stok fiyatı',
                'verbose_name_plural': 'stok fiyatları',
                'db_table': 'stok_fiyat',
                'ordering': ['stok', 'para_birimi'],
            },
        ),
        migrations.AddField(
            model_name='teklifsiparis',
            name='odeme_kosulu',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='ödeme koşulu'),
        ),
        migrations.AddField(
            model_name='teklifsiparis',
            name='teslim_sekli',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='teslim / nakliye / yükleme şekli'),
        ),
        migrations.AddField(
            model_name='teklifsipariskalem',
            name='iskonto_yuzdesi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='iskonto %'),
        ),
        migrations.AddConstraint(
            model_name='teklifsipariskalem',
            constraint=models.CheckConstraint(condition=models.Q(('iskonto_yuzdesi__gte', 0), ('iskonto_yuzdesi__lte', 100)), name='ck_ts_kalem_iskonto_0_100'),
        ),
        migrations.AddField(
            model_name='stokfiyat',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan'),
        ),
        migrations.AddField(
            model_name='stokfiyat',
            name='stok',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiyatlar', to='core.stok', verbose_name='stok'),
        ),
        migrations.AddField(
            model_name='stokfiyat',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen'),
        ),
        migrations.AddConstraint(
            model_name='stokfiyat',
            constraint=models.UniqueConstraint(condition=models.Q(('silindi', False)), fields=('stok', 'para_birimi'), name='uq_stok_fiyat_stok_pb_aktif'),
        ),
        migrations.AddConstraint(
            model_name='stokfiyat',
            constraint=models.CheckConstraint(condition=models.Q(('fiyat__gte', 0)), name='ck_stok_fiyat_gte0'),
        ),
    ]
