# Generated by Django 6.0.5 on 2026-09-07 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_stokfiyat_teklifsiparis_odeme_kosulu_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teklifsiparis',
            name='teslim_sekli',
        ),
        migrations.AddField(
            model_name='teklifsiparis',
            name='navlun_tutari',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='navlun tutarı'),
        ),
        migrations.CreateModel(
            name='TanimSecenegi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('kategori', models.CharField(choices=[('YUKLEME_SEKLI', 'Yükleme Şekli'), ('ODEME_KOSULU', 'Ödeme Koşulu'), ('YUKLEME_TIPI', 'Yükleme Tipi')], max_length=15, verbose_name='kategori')),
                ('kod', models.CharField(blank=True, default='', max_length=30, verbose_name='kod')),
                ('ad', models.CharField(max_length=200, verbose_name='ad')),
                ('sira', models.PositiveSmallIntegerField(default=0, verbose_name='sıra')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'tanım seçeneği',
                'verbose_name_plural': 'tanım seçenekleri',
                'db_table': 'tanim_secenegi',
                'ordering': ['kategori', 'sira', 'ad'],
            },
        ),
        migrations.AddField(
            model_name='teklifsiparis',
            name='yukleme_sekli',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.tanimsecenegi', verbose_name='yükleme şekli'),
        ),
        migrations.AddField(
            model_name='teklifsiparis',
            name='yukleme_tipi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.tanimsecenegi', verbose_name='yükleme tipi'),
        ),
        # CharField -> FK: AlterField PostgreSQL'de metin sütununu bigint'e çeviremez;
        # alan yeni ve canlıda dolu kayıt yok (doğrulandı) — kaldır + yeniden ekle.
        migrations.RemoveField(
            model_name='teklifsiparis',
            name='odeme_kosulu',
        ),
        migrations.AddField(
            model_name='teklifsiparis',
            name='odeme_kosulu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.tanimsecenegi', verbose_name='ödeme koşulu'),
        ),
        migrations.AddConstraint(
            model_name='teklifsiparis',
            constraint=models.CheckConstraint(condition=models.Q(('navlun_tutari__isnull', True), ('navlun_tutari__gte', 0), _connector='OR'), name='ck_teklif_siparis_navlun_gte0'),
        ),
        migrations.AddConstraint(
            model_name='tanimsecenegi',
            constraint=models.UniqueConstraint(condition=models.Q(('silindi', False)), fields=('kategori', 'ad'), name='uq_tanim_secenegi_kategori_ad_aktif'),
        ),
        migrations.AddConstraint(
            model_name='tanimsecenegi',
            constraint=models.UniqueConstraint(condition=models.Q(('silindi', False), models.Q(('kod', ''), _negated=True)), fields=('kategori', 'kod'), name='uq_tanim_secenegi_kategori_kod_aktif'),
        ),
    ]
