# Generated by Django 6.0.5 on 2026-09-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_tanim_secenegi_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanimsecenegi',
            name='ad_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='ad (İngilizce)'),
        ),
    ]
