# Generated by Django 6.0.5 on 2026-09-08 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_tanim_secenegi_ad_en_seed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmaBilgisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('unvan', models.CharField(blank=True, max_length=200, verbose_name='unvan')),
                ('vergi_dairesi', models.CharField(blank=True, max_length=100, verbose_name='vergi dairesi')),
                ('vergi_no', models.CharField(blank=True, max_length=20, verbose_name='vergi no')),
                ('adres', models.TextField(blank=True, verbose_name='adres')),
                ('telefon', models.CharField(blank=True, max_length=30, verbose_name='telefon')),
                ('eposta', models.EmailField(blank=True, max_length=254, verbose_name='e-posta')),
                ('web', models.CharField(blank=True, max_length=200, verbose_name='web sitesi')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='firma_logo/', verbose_name='logo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'firma bilgisi',
                'verbose_name_plural': 'firma bilgisi',
                'db_table': 'core_firma_bilgisi',
            },
        ),
        migrations.CreateModel(
            name='FirmaBanka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('banka_adi', models.CharField(max_length=100, verbose_name='banka')),
                ('sube', models.CharField(blank=True, max_length=100, verbose_name='şube')),
                ('hesap_sahibi', models.CharField(blank=True, max_length=200, verbose_name='hesap sahibi')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('para_birimi', models.CharField(choices=[('TRY', 'TRY'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='TRY', max_length=3, verbose_name='para birimi')),
                ('sira', models.PositiveSmallIntegerField(default=0, verbose_name='sıra')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankalar', to='core.firmabilgisi', verbose_name='firma')),
            ],
            options={
                'verbose_name': 'firma banka hesabı',
                'verbose_name_plural': 'firma banka hesapları',
                'db_table': 'core_firma_banka',
                'ordering': ['sira', 'pk'],
            },
        ),
    ]
