# Generated by Django 6.0.5 on 2026-09-08 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_firma_bilgisi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FasonKesim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('parca_adi', models.CharField(max_length=50, verbose_name='parça adı')),
                ('adet', models.PositiveSmallIntegerField(default=1, verbose_name='adet (1 ürün için)')),
                ('sira', models.PositiveSmallIntegerField(default=0, verbose_name='sıra')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fason_kesimleri', to='core.stok', verbose_name='profil (hammadde)')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
                ('urunler', models.ManyToManyField(blank=True, related_name='fason_kesim_gereksinimleri', to='core.stok', verbose_name='uygulandığı ürünler')),
            ],
            options={
                'verbose_name': 'fason kesim satırı',
                'verbose_name_plural': 'fason kesim satırları',
                'db_table': 'core_fason_kesim',
                'ordering': ['sira', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('adet__gte', 1)), name='ck_fason_kesim_adet_gte1')],
            },
        ),
    ]
