# Generated by Django 6.0.5 on 2026-09-08 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_fason_kesim_wrong_veri_temizle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fasonkesim',
            name='parca_adi',
        ),
        migrations.RemoveField(
            model_name='fasonkesim',
            name='profil',
        ),
        migrations.RemoveField(
            model_name='fasonkesim',
            name='urunler',
        ),
        migrations.AddField(
            model_name='fasonkesim',
            name='kesilmis_parca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fason_kullanimlari', to='core.stok', verbose_name='kesilmiş parça'),
        ),
        migrations.AddField(
            model_name='fasonkesim',
            name='urun',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fason_kesimleri', to='core.stok', verbose_name='ürün (bitmiş)'),
        ),
        migrations.AddField(
            model_name='stok',
            name='kesildigi_profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kesilen_parcalar', to='core.stok', verbose_name='kesildiği ham profil'),
        ),
        migrations.AddConstraint(
            model_name='fasonkesim',
            constraint=models.UniqueConstraint(condition=models.Q(('silindi', False)), fields=('urun', 'kesilmis_parca'), name='uq_fason_kesim_urun_parca_aktif'),
        ),
    ]
