# Generated by Django 6.0.5 on 2026-09-08 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_fason_kesim_seed_dogru'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FasonKesimKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('yil', models.PositiveSmallIntegerField(editable=False, verbose_name='yıl')),
                ('sira', models.PositiveIntegerField(editable=False, verbose_name='sıra')),
                ('no', models.CharField(editable=False, max_length=20, verbose_name='kayıt no')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'fason kesim kaydı',
                'verbose_name_plural': 'fason kesim kayıtları',
                'db_table': 'core_fason_kesim_kaydi',
                'ordering': ['-yil', '-sira'],
            },
        ),
        migrations.CreateModel(
            name='FasonKesimKaydiKalemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('miktar', models.PositiveIntegerField(verbose_name='miktar')),
                ('sira', models.PositiveSmallIntegerField(default=0, verbose_name='sıra')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('kayit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalemler', to='core.fasonkesimkaydi')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.stok', verbose_name='ürün (bitmiş)')),
            ],
            options={
                'verbose_name': 'fason kesim kaydı satırı',
                'verbose_name_plural': 'fason kesim kaydı satırları',
                'db_table': 'core_fason_kesim_kaydi_kalemi',
                'ordering': ['sira', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='fasonkesimkaydi',
            constraint=models.UniqueConstraint(fields=('yil', 'sira'), name='uq_fason_kesim_kaydi_yil_sira'),
        ),
        migrations.AddConstraint(
            model_name='fasonkesimkaydikalemi',
            constraint=models.CheckConstraint(condition=models.Q(('miktar__gte', 1)), name='ck_fason_kesim_kaydi_kalemi_miktar_gte1'),
        ),
    ]
