# Generated by Django 6.0.5 on 2026-09-09 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_fason_kesim_kaydi'),
    ]

    operations = [
        migrations.AddField(
            model_name='stok',
            name='ad_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='ad (İngilizce)'),
        ),
        migrations.AddField(
            model_name='teklifsiparis',
            name='teslim_suresi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.tanimsecenegi', verbose_name='teslim süresi'),
        ),
        migrations.AlterField(
            model_name='tanimsecenegi',
            name='kategori',
            field=models.CharField(choices=[('YUKLEME_SEKLI', 'Yükleme Şekli'), ('ODEME_KOSULU', 'Ödeme Koşulu'), ('YUKLEME_TIPI', 'Yükleme Tipi'), ('TESLIM_SURESI', 'Teslim Süresi')], max_length=15, verbose_name='kategori'),
        ),
    ]
