# Generated by Django 6.0.5 on 2026-09-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_tanim_secenegi_exw_fob_en_duzelt'),
    ]

    operations = [
        migrations.AddField(
            model_name='stok',
            name='hs_kodu',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='H/S kodu'),
        ),
        migrations.AddField(
            model_name='stok',
            name='materyal',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='materyal'),
        ),
        migrations.AddField(
            model_name='stok',
            name='materyal_en',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='materyal (İngilizce)'),
        ),
    ]
