# Generated by Django 6.0.5 on 2026-09-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_stok_materyal_en_buyuk_harf'),
    ]

    operations = [
        migrations.AddField(
            model_name='cari',
            name='ilgili_kisi',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='adı soyadı'),
        ),
    ]
