# Generated by Django 6.0.5 on 2026-09-11 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_cari_ilgili_kisi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tanimsecenegi',
            name='varsayilan',
            field=models.BooleanField(default=False, verbose_name='varsayılan'),
        ),
        migrations.AddConstraint(
            model_name='tanimsecenegi',
            constraint=models.UniqueConstraint(condition=models.Q(('silindi', False), ('varsayilan', True)), fields=('kategori',), name='uq_tanim_secenegi_varsayilan_kategori'),
        ),
    ]
