# Generated by Django 6.0.5 on 2026-09-11 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_tanim_secenegi_varsayilan_seed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanimsecenegi',
            name='kategori',
            field=models.CharField(choices=[('YUKLEME_SEKLI', 'Yükleme Şekli'), ('ODEME_KOSULU', 'Ödeme Koşulu'), ('YUKLEME_TIPI', 'Yükleme Tipi'), ('TESLIM_SURESI', 'Teslim Süresi'), ('ADAY_KAYNAGI', 'Aday Kaynağı')], max_length=15, verbose_name='kategori'),
        ),
        migrations.CreateModel(
            name='AdayMusteri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('unvan', models.CharField(max_length=200, verbose_name='unvan / ad soyad')),
                ('ilgili_kisi', models.CharField(blank=True, default='', max_length=120, verbose_name='ilgili kişi')),
                ('telefon', models.CharField(blank=True, default='', max_length=20, verbose_name='telefon')),
                ('eposta', models.EmailField(blank=True, default='', max_length=254, verbose_name='e-posta')),
                ('asama', models.CharField(choices=[('YENI', 'Yeni'), ('ILETISIMDE', 'İletişimde'), ('TEKLIF_VERILDI', 'Teklif Verildi'), ('MUZAKERE', 'Müzakere'), ('KAZANILDI', 'Kazanıldı'), ('KAYBEDILDI', 'Kaybedildi')], default='YENI', max_length=15, verbose_name='aşama')),
                ('tahmini_deger', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='tahmini değer')),
                ('para_birimi', models.CharField(choices=[('TRY', 'TRY'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='TRY', max_length=3, verbose_name='para birimi')),
                ('sonraki_takip_tarihi', models.DateField(blank=True, null=True, verbose_name='sonraki takip tarihi')),
                ('kaybedilme_nedeni', models.CharField(blank=True, default='', max_length=200, verbose_name='kaybedilme nedeni')),
                ('notlar', models.TextField(blank=True, default='', verbose_name='notlar')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('donusen_cari', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aday_kaynagi', to='core.cari', verbose_name='dönüşen cari')),
                ('kaynak', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.tanimsecenegi', verbose_name='kaynak')),
                ('sehir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aday_musteriler', to='core.sehir', verbose_name='şehir')),
                ('sorumlu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sorumlu_adaylar', to=settings.AUTH_USER_MODEL, verbose_name='sorumlu')),
                ('ulke', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aday_musteriler', to='core.ulke', verbose_name='ülke')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'aday müşteri',
                'verbose_name_plural': 'aday müşteriler',
                'db_table': 'aday_musteri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdayAktivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('tarih', models.DateField(verbose_name='tarih')),
                ('tur', models.CharField(choices=[('GORUSME', 'Görüşme'), ('TELEFON', 'Telefon'), ('TOPLANTI', 'Toplantı'), ('EPOSTA', 'E-posta'), ('NOT', 'Not')], default='NOT', max_length=10, verbose_name='tür')),
                ('aciklama', models.TextField(verbose_name='açıklama')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
                ('aday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aktiviteler', to='core.adaymusteri', verbose_name='aday')),
            ],
            options={
                'verbose_name': 'aday aktivite',
                'verbose_name_plural': 'aday aktiviteler',
                'db_table': 'aday_aktivite',
                'ordering': ['-tarih', '-id'],
            },
        ),
    ]
