# Generated by Django 6.0.5 on 2026-09-13 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_tanim_secenegi_aday_kaynagi_seed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adaymusteri',
            name='asama',
        ),
        migrations.RemoveField(
            model_name='adaymusteri',
            name='kaybedilme_nedeni',
        ),
        migrations.RemoveField(
            model_name='adaymusteri',
            name='kaynak',
        ),
        migrations.RemoveField(
            model_name='adaymusteri',
            name='notlar',
        ),
        migrations.RemoveField(
            model_name='adaymusteri',
            name='sonraki_takip_tarihi',
        ),
        migrations.RemoveField(
            model_name='adaymusteri',
            name='sorumlu',
        ),
        migrations.RemoveField(
            model_name='adaymusteri',
            name='tahmini_deger',
        ),
        migrations.AddField(
            model_name='adaymusteri',
            name='iskonto_yuzdesi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='varsayılan iskonto %'),
        ),
        migrations.AlterField(
            model_name='tanimsecenegi',
            name='kategori',
            field=models.CharField(choices=[('YUKLEME_SEKLI', 'Yükleme Şekli'), ('ODEME_KOSULU', 'Ödeme Koşulu'), ('YUKLEME_TIPI', 'Yükleme Tipi'), ('TESLIM_SURESI', 'Teslim Süresi')], max_length=15, verbose_name='kategori'),
        ),
        migrations.CreateModel(
            name='AdayMusteriKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('ad', models.CharField(max_length=100, verbose_name='ad')),
                ('kod', models.CharField(max_length=10, verbose_name='kod')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
                ('ust', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alt_kategoriler', to='core.adaymusterikategori', verbose_name='üst kategori')),
            ],
            options={
                'verbose_name': 'aday müşteri kategorisi',
                'verbose_name_plural': 'aday müşteri kategorileri',
                'db_table': 'aday_musteri_kategori',
                'ordering': ['kod'],
            },
        ),
        migrations.AddField(
            model_name='adaymusteri',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aday_musteriler', to='core.adaymusterikategori', verbose_name='kategori'),
        ),
        migrations.AddConstraint(
            model_name='adaymusterikategori',
            constraint=models.UniqueConstraint(condition=models.Q(('silindi', False)), fields=('ust', 'kod'), name='uq_adaykat_ust_kod_aktif', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='adaymusterikategori',
            constraint=models.UniqueConstraint(condition=models.Q(('silindi', False)), fields=('ust', 'ad'), name='uq_adaykat_ust_ad_aktif', nulls_distinct=False),
        ),
    ]
