# Generated by Django 6.0.5 on 2026-09-13 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_tanim_secenegi_aday_kaynagi_temizle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdayAktiviteEk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('dosya', models.FileField(upload_to='aday_aktivite/', verbose_name='dosya')),
                ('orijinal_ad', models.CharField(blank=True, max_length=255, verbose_name='orijinal dosya adı')),
                ('aktivite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ekler', to='core.adayaktivite', verbose_name='aktivite')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'aktivite eki',
                'verbose_name_plural': 'aktivite ekleri',
                'db_table': 'aday_aktivite_ek',
                'ordering': ['id'],
            },
        ),
    ]
