# Generated by Django 6.0.5 on 2026-09-13 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_aday_aktivite_ek'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teklifsiparis',
            name='aday_musteri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teklif_siparisler', to='core.adaymusteri', verbose_name='aday müşteri'),
        ),
        migrations.AlterField(
            model_name='teklifsiparis',
            name='cari',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teklif_siparisler', to='core.cari', verbose_name='cari'),
        ),
        migrations.AddConstraint(
            model_name='teklifsiparis',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('aday_musteri__isnull', True), ('cari__isnull', False)), models.Q(('aday_musteri__isnull', False), ('cari__isnull', True)), _connector='OR'), name='ck_teklif_siparis_cari_xor_aday_musteri'),
        ),
    ]
