# Generated by Django 6.0.5 on 2026-09-15 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_teklif_siparis_aday_musteri'),
    ]

    operations = [
        migrations.AddField(
            model_name='teklifsiparis',
            name='kaynak_proforma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donusen_siparisler', to='core.teklifsiparis', verbose_name='kaynak proforma'),
        ),
        migrations.AlterField(
            model_name='teklifsiparis',
            name='belge_tur',
            field=models.CharField(choices=[('TEKLIF', 'Teklif'), ('PROFORMA', 'Proforma'), ('SIPARIS', 'Sipariş'), ('IRSALIYE', 'İrsaliye')], max_length=8, verbose_name='belge türü'),
        ),
        migrations.AlterField(
            model_name='teklifsiparis',
            name='kaynak_teklif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donusen_belgeler', to='core.teklifsiparis', verbose_name='kaynak teklif'),
        ),
    ]
