# Generated by Django 6.0.5 on 2026-09-15 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_teklif_siparis_proforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='teklifsiparis',
            name='banka_hesabi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teklif_siparisler', to='core.firmabanka', verbose_name='banka hesabı'),
        ),
    ]
