# Generated by Django 6.0.5 on 2026-09-15 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_teklif_siparis_banka_hesabi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teklifsiparis',
            name='banka_hesabi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teklif_siparisler', to='core.bankahesap', verbose_name='banka hesabı'),
        ),
    ]
