# Generated by Django 6.0.5 on 2026-09-15 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_teklif_siparis_banka_hesabi_bankahesap'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stokhareket',
            name='kaynak',
            field=models.CharField(choices=[('MANUEL', 'Manuel'), ('FATURA', 'Fatura'), ('IRSALIYE', 'İrsaliye'), ('URETIM', 'Üretim')], default='MANUEL', max_length=20, verbose_name='kaynak'),
        ),
        migrations.CreateModel(
            name='UretimEmri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('yil', models.PositiveSmallIntegerField(editable=False, verbose_name='yıl')),
                ('sira', models.PositiveIntegerField(editable=False, verbose_name='sıra')),
                ('no', models.CharField(editable=False, max_length=20, verbose_name='emir no')),
                ('tarih', models.DateField(verbose_name='tarih')),
                ('planlanan_miktar', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='planlanan miktar')),
                ('durum', models.CharField(choices=[('TASLAK', 'Taslak'), ('ONAYLI', 'Onaylı')], default='TASLAK', max_length=6, verbose_name='durum')),
                ('aciklama', models.CharField(blank=True, default='', max_length=300, verbose_name='açıklama')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('depo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uretim_emirleri', to='core.depo', verbose_name='depo')),
                ('mamul', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uretim_emirleri', to='core.stok', verbose_name='mamul')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'üretim emri',
                'verbose_name_plural': 'üretim emirleri',
                'db_table': 'core_uretim_emri',
                'ordering': ['-yil', '-sira'],
            },
        ),
        migrations.CreateModel(
            name='UretimEmriSatir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('planlanan_miktar', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='planlanan miktar')),
                ('gerceklesen_miktar', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='gerçekleşen miktar')),
                ('sira', models.PositiveSmallIntegerField(default=0, verbose_name='sıra')),
                ('bilesen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uretim_emri_kullanimlari', to='core.stok', verbose_name='bileşen')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('emir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satirlar', to='core.uretimemri')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'üretim emri satırı',
                'verbose_name_plural': 'üretim emri satırları',
                'db_table': 'core_uretim_emri_satir',
                'ordering': ['sira', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='stokhareket',
            name='uretim_emri_satir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stok_hareketleri', to='core.uretimemrisatir', verbose_name='kaynak üretim emri satırı'),
        ),
        migrations.CreateModel(
            name='UrunAgaci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('aciklama', models.CharField(blank=True, default='', max_length=300, verbose_name='açıklama')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('mamul', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='urun_agaclari', to='core.stok', verbose_name='mamul')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'ürün ağacı',
                'verbose_name_plural': 'ürün ağaçları',
                'db_table': 'core_urun_agaci',
                'ordering': ['mamul__kod'],
            },
        ),
        migrations.AddField(
            model_name='uretimemri',
            name='urun_agaci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uretim_emirleri', to='core.urunagaci', verbose_name='ürün ağacı'),
        ),
        migrations.CreateModel(
            name='UrunAgaciSatir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('miktar', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='miktar (1 mamul için)')),
                ('sira', models.PositiveSmallIntegerField(default=0, verbose_name='sıra')),
                ('bilesen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='urun_agaci_kullanimlari', to='core.stok', verbose_name='bileşen')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
                ('urun_agaci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satirlar', to='core.urunagaci')),
            ],
            options={
                'verbose_name': 'ürün ağacı satırı',
                'verbose_name_plural': 'ürün ağacı satırları',
                'db_table': 'core_urun_agaci_satir',
                'ordering': ['sira', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='uretimemrisatir',
            constraint=models.CheckConstraint(condition=models.Q(('planlanan_miktar__gt', 0)), name='ck_uretim_emri_satir_planlanan_miktar_gt0'),
        ),
        migrations.AddConstraint(
            model_name='uretimemrisatir',
            constraint=models.CheckConstraint(condition=models.Q(('gerceklesen_miktar__gte', 0)), name='ck_uretim_emri_satir_gerceklesen_miktar_gte0'),
        ),
        migrations.AddConstraint(
            model_name='urunagaci',
            constraint=models.UniqueConstraint(condition=models.Q(('silindi', False)), fields=('mamul',), name='uq_urun_agaci_mamul_aktif'),
        ),
        migrations.AddConstraint(
            model_name='uretimemri',
            constraint=models.UniqueConstraint(fields=('yil', 'sira'), name='uq_uretim_emri_yil_sira'),
        ),
        migrations.AddConstraint(
            model_name='uretimemri',
            constraint=models.CheckConstraint(condition=models.Q(('planlanan_miktar__gt', 0)), name='ck_uretim_emri_planlanan_miktar_gt0'),
        ),
        migrations.AddConstraint(
            model_name='urunagacisatir',
            constraint=models.CheckConstraint(condition=models.Q(('miktar__gt', 0)), name='ck_urun_agaci_satir_miktar_gt0'),
        ),
        migrations.AddConstraint(
            model_name='urunagacisatir',
            constraint=models.UniqueConstraint(condition=models.Q(('silindi', False)), fields=('urun_agaci', 'bilesen'), name='uq_urun_agaci_satir_bilesen_aktif'),
        ),
    ]
