# Generated by Django 6.0.5 on 2026-09-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_operasyon_routing'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaymusteri',
            name='eposta_2',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='e-posta 2'),
        ),
        migrations.AddField(
            model_name='adaymusteri',
            name='telefon_2',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='telefon 2'),
        ),
    ]
