# Generated by Django 6.0.5 on 2026-09-18 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_adaymusteri_eposta_2_adaymusteri_telefon_2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StokMaliyetKatmani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('tarih', models.DateField(verbose_name='tarih')),
                ('giris_miktar', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='giriş miktarı')),
                ('kalan_miktar', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='kalan miktar')),
                ('birim_maliyet_try', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='birim maliyet (TL)')),
                ('kaynak_pb', models.CharField(blank=True, default='', max_length=3, verbose_name='kaynak para birimi')),
                ('kaynak_birim_fiyat', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='kaynak birim fiyat')),
                ('kaynak_kur', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='kaynak kur')),
                ('tahmini', models.BooleanField(default=False, verbose_name='tahmini/eksik veri')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('depo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maliyet_katmanlari', to='core.depo', verbose_name='depo')),
                ('stok', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maliyet_katmanlari', to='core.stok', verbose_name='stok')),
                ('stok_hareket', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='maliyet_katmani', to='core.stokhareket', verbose_name='kaynak stok hareketi')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'stok maliyet katmanı',
                'verbose_name_plural': 'stok maliyet katmanları',
                'db_table': 'stok_maliyet_katmani',
            },
        ),
        migrations.CreateModel(
            name='StokMaliyetTuketimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('miktar', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='miktar')),
                ('birim_maliyet_try', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='birim maliyet (TL, snapshot)')),
                ('tutar_try', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='tutar (TL)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('katman', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tuketimler', to='core.stokmaliyetkatmani', verbose_name='katman')),
                ('tuketen_hareket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maliyet_tuketimleri', to='core.stokhareket', verbose_name='tüketen hareket')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'stok maliyet tüketimi',
                'verbose_name_plural': 'stok maliyet tüketimleri',
                'db_table': 'stok_maliyet_tuketimi',
            },
        ),
        migrations.AddIndex(
            model_name='stokmaliyetkatmani',
            index=models.Index(condition=models.Q(('kalan_miktar__gt', 0), ('silindi', False)), fields=['stok', 'depo', 'tarih', 'id'], name='idx_maliyet_katman_fifo'),
        ),
        migrations.AddConstraint(
            model_name='stokmaliyetkatmani',
            constraint=models.CheckConstraint(condition=models.Q(('giris_miktar__gt', 0)), name='ck_katman_giris_gt0'),
        ),
        migrations.AddConstraint(
            model_name='stokmaliyetkatmani',
            constraint=models.CheckConstraint(condition=models.Q(('kalan_miktar__gte', 0)), name='ck_katman_kalan_gte0'),
        ),
        migrations.AddConstraint(
            model_name='stokmaliyetkatmani',
            constraint=models.CheckConstraint(condition=models.Q(('birim_maliyet_try__gte', 0)), name='ck_katman_maliyet_gte0'),
        ),
        migrations.AddConstraint(
            model_name='stokmaliyettuketimi',
            constraint=models.CheckConstraint(condition=models.Q(('miktar__gt', 0)), name='ck_tuketim_miktar_gt0'),
        ),
    ]
