# Generated by Django 6.0.5 on 2026-09-18 11:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_stokmaliyetkatmani_stokmaliyettuketimi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teklifsipariskalem',
            name='uretim_miktar',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='üretim miktarı'),
        ),
        migrations.AddConstraint(
            model_name='teklifsipariskalem',
            constraint=models.CheckConstraint(condition=models.Q(('uretim_miktar__isnull', True), ('uretim_miktar__gt', 0), _connector='OR'), name='ck_ts_kalem_uretim_miktar_gt0'),
        ),
    ]
