# Generated by Django 6.0.5 on 2026-09-18 13:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_teklifsipariskalem_uretim_miktar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cari',
            name='kur_tipi',
            field=models.CharField(choices=[('MB_ALIS', 'MB Alış'), ('MB_SATIS', 'MB Satış'), ('EFEKTIF_ALIS', 'Efektif Alış'), ('EFEKTIF_SATIS', 'Efektif Satış')], default='MB_ALIS', max_length=15, verbose_name='kur tipi'),
        ),
        migrations.AddField(
            model_name='teklifsiparis',
            name='kur',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='kur (TL)'),
        ),
        migrations.AddConstraint(
            model_name='teklifsiparis',
            constraint=models.CheckConstraint(condition=models.Q(('kur__isnull', True), ('kur__gt', 0), _connector='OR'), name='ck_teklif_siparis_kur_gt0'),
        ),
    ]
