# Generated by Django 6.0.5 on 2026-09-18 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_cari_kur_tipi_teklifsiparis_kur_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UretimEmriKalemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('hedef_miktar', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='hedef miktar')),
                ('sira', models.PositiveSmallIntegerField(default=0, verbose_name='sıra')),
            ],
            options={
                'verbose_name': 'üretim emri kalemi',
                'verbose_name_plural': 'üretim emri kalemleri',
                'db_table': 'core_uretim_emri_kalemi',
                'ordering': ['sira', 'pk'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='uretimemri',
            name='ck_uretim_emri_hedef_miktar_gt0',
        ),
        migrations.AddField(
            model_name='uretimemri',
            name='kaynak_siparis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uretim_emirleri', to='core.teklifsiparis', verbose_name='kaynak sipariş'),
        ),
        migrations.AddField(
            model_name='uretimemrikalemi',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan'),
        ),
        migrations.AddField(
            model_name='uretimemrikalemi',
            name='hedef_urun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uretim_emri_kalemleri', to='core.stok', verbose_name='hedef ürün'),
        ),
        migrations.AddField(
            model_name='uretimemrikalemi',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen'),
        ),
        migrations.AddField(
            model_name='uretimemrikalemi',
            name='uretim_emri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalemler', to='core.uretimemri', verbose_name='üretim emri'),
        ),
        migrations.RemoveField(
            model_name='uretimemri',
            name='hedef_miktar',
        ),
        migrations.RemoveField(
            model_name='uretimemri',
            name='hedef_urun',
        ),
        migrations.AddConstraint(
            model_name='uretimemrikalemi',
            constraint=models.CheckConstraint(condition=models.Q(('hedef_miktar__gt', 0)), name='ck_uretim_emri_kalemi_hedef_miktar_gt0'),
        ),
    ]
