# Generated by Django 6.0.5 on 2026-09-19 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_uretimemrikalemi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('ad', models.CharField(max_length=100, verbose_name='ad')),
                ('soyad', models.CharField(max_length=100, verbose_name='soyad')),
                ('tc_kimlik_no', models.CharField(blank=True, max_length=11, verbose_name='TC kimlik no')),
                ('dogum_tarihi', models.DateField(blank=True, null=True, verbose_name='doğum tarihi')),
                ('kan_grubu', models.CharField(blank=True, choices=[('0+', '0+'), ('0-', '0-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, verbose_name='kan grubu')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='telefon')),
                ('eposta', models.EmailField(blank=True, max_length=254, verbose_name='e-posta')),
                ('adres', models.TextField(blank=True, verbose_name='adres')),
                ('acil_durum_kisi', models.CharField(blank=True, max_length=120, verbose_name='acil durumda aranacak kişi')),
                ('acil_durum_telefon', models.CharField(blank=True, max_length=20, verbose_name='acil durum telefonu')),
                ('departman', models.CharField(blank=True, max_length=80, verbose_name='departman')),
                ('gorev', models.CharField(blank=True, max_length=80, verbose_name='görev')),
                ('ise_giris_tarihi', models.DateField(verbose_name='işe giriş tarihi')),
                ('isten_cikis_tarihi', models.DateField(blank=True, null=True, verbose_name='işten çıkış tarihi')),
                ('cikis_nedeni', models.CharField(blank=True, max_length=200, verbose_name='çıkış nedeni')),
                ('notlar', models.TextField(blank=True, verbose_name='notlar')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'personel',
                'verbose_name_plural': 'personel',
                'db_table': 'core_personel',
                'ordering': ['ad', 'soyad'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('silindi', False), models.Q(('tc_kimlik_no', ''), _negated=True)), fields=('tc_kimlik_no',), name='uq_personel_tc_dolu'), models.CheckConstraint(condition=models.Q(('isten_cikis_tarihi__isnull', True), ('isten_cikis_tarihi__gte', models.F('ise_giris_tarihi')), _connector='OR'), name='ck_personel_cikis_gte_giris')],
            },
        ),
    ]
