# Generated by Django 6.0.5 on 2026-09-19 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0118_personel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonelIzin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('tur', models.CharField(choices=[('YILLIK', 'Yıllık İzin'), ('RAPOR', 'Rapor'), ('MAZERET', 'Mazeret İzni'), ('UCRETSIZ', 'Ücretsiz İzin'), ('DIGER', 'Diğer')], default='YILLIK', max_length=10, verbose_name='tür')),
                ('baslangic', models.DateField(verbose_name='başlangıç')),
                ('bitis', models.DateField(verbose_name='bitiş')),
                ('gun', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='gün')),
                ('aciklama', models.CharField(blank=True, max_length=300, verbose_name='açıklama')),
            ],
            options={
                'verbose_name': 'personel izni',
                'verbose_name_plural': 'personel izinleri',
                'db_table': 'core_personel_izin',
                'ordering': ['-baslangic', '-id'],
            },
        ),
        migrations.AddField(
            model_name='personel',
            name='izin_onceki_kullanilan',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='sisteme geçmeden önce kullanılan yıllık izin (gün)'),
        ),
        migrations.AddConstraint(
            model_name='personel',
            constraint=models.CheckConstraint(condition=models.Q(('izin_onceki_kullanilan__gte', 0)), name='ck_personel_izin_onceki_gte0'),
        ),
        migrations.AddField(
            model_name='personelizin',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan'),
        ),
        migrations.AddField(
            model_name='personelizin',
            name='personel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='izinler', to='core.personel', verbose_name='personel'),
        ),
        migrations.AddField(
            model_name='personelizin',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen'),
        ),
        migrations.AddIndex(
            model_name='personelizin',
            index=models.Index(fields=['personel', 'baslangic'], name='ix_personel_izin_kisi_bas'),
        ),
        migrations.AddConstraint(
            model_name='personelizin',
            constraint=models.CheckConstraint(condition=models.Q(('bitis__gte', models.F('baslangic'))), name='ck_personel_izin_bitis_gte_baslangic'),
        ),
        migrations.AddConstraint(
            model_name='personelizin',
            constraint=models.CheckConstraint(condition=models.Q(('gun__gt', 0)), name='ck_personel_izin_gun_gt0'),
        ),
    ]
