# Generated by Django 6.0.5 on 2026-09-19 21:49

import core.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_personel_izin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='foto',
            field=models.FileField(blank=True, storage=core.storage.ik_ozel_depo, upload_to=core.storage.personel_foto_yolu, verbose_name='fotoğraf'),
        ),
        migrations.CreateModel(
            name='PersonelBelge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('tur', models.CharField(choices=[('KIMLIK', 'Kimlik'), ('SAGLIK_RAPORU', 'Sağlık Raporu'), ('SOZLESME', 'İş Sözleşmesi'), ('SGK_GIRIS', 'SGK İşe Giriş Belgesi'), ('ISG_EGITIMI', 'İSG Eğitim Belgesi'), ('OPERATOR_BELGESI', 'Operatör / Yeterlilik Belgesi'), ('EHLIYET', 'Ehliyet'), ('DIPLOMA', 'Diploma / Sertifika'), ('DIGER', 'Diğer')], max_length=20, verbose_name='tür')),
                ('aciklama', models.CharField(blank=True, max_length=200, verbose_name='açıklama')),
                ('dosya', models.FileField(storage=core.storage.ik_ozel_depo, upload_to=core.storage.personel_belge_yolu, verbose_name='dosya')),
                ('orijinal_ad', models.CharField(max_length=255, verbose_name='özgün dosya adı')),
                ('bitis_tarihi', models.DateField(blank=True, null=True, verbose_name='geçerlilik bitiş tarihi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='belgeler', to='core.personel', verbose_name='personel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'personel belgesi',
                'verbose_name_plural': 'personel belgeleri',
                'db_table': 'core_personel_belge',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['personel', 'tur'], name='ix_personel_belge_kisi_tur')],
            },
        ),
    ]
