# Generated by Django 6.0.5 on 2026-09-19 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_personel_belge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonelDevam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('tarih', models.DateField(verbose_name='tarih')),
                ('durum', models.CharField(choices=[('GELDI', 'Geldi'), ('GELMEDI', 'Gelmedi'), ('YARIM_GUN', 'Yarım Gün')], max_length=10, verbose_name='durum')),
                ('notlar', models.CharField(blank=True, max_length=200, verbose_name='not')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devam_kayitlari', to='core.personel', verbose_name='personel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'personel devam kaydı',
                'verbose_name_plural': 'personel devam kayıtları',
                'db_table': 'core_personel_devam',
                'ordering': ['-tarih', '-id'],
                'indexes': [models.Index(fields=['tarih'], name='ix_personel_devam_tarih')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('silindi', False)), fields=('personel', 'tarih'), name='uq_personel_devam_aktif')],
            },
        ),
    ]
