# Generated by Django 6.0.5 on 2026-09-20 18:12

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_personel_devam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adayaktiviteek',
            name='dosya',
            field=models.FileField(storage=core.storage.ozel_depo, upload_to=core.storage.aday_ek_yolu, verbose_name='dosya'),
        ),
        migrations.AlterField(
            model_name='cariaktiviteek',
            name='dosya',
            field=models.FileField(storage=core.storage.ozel_depo, upload_to=core.storage.cari_ek_yolu, verbose_name='dosya'),
        ),
        migrations.AlterField(
            model_name='ceksenet',
            name='arka_yuz',
            field=models.ImageField(blank=True, null=True, storage=core.storage.ozel_depo, upload_to=core.storage.cek_gorsel_yolu, verbose_name='arka yüz görseli'),
        ),
        migrations.AlterField(
            model_name='ceksenet',
            name='on_yuz',
            field=models.ImageField(blank=True, null=True, storage=core.storage.ozel_depo, upload_to=core.storage.cek_gorsel_yolu, verbose_name='ön yüz görseli'),
        ),
    ]
