# Generated by Django 6.0.5 on 2026-09-20 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def gider_tipini_isaretle(apps, schema_editor):
    """Var olan 'ALIŞ FATURASI-GİDER' tipini (yön ALIŞ) gider faturası olarak işaretler.
    Tip yoksa (taze kurulum/test) hiçbir şey yapmaz."""
    FaturaTipi = apps.get_model("core", "FaturaTipi")
    FaturaTipi.objects.filter(
        silindi=False, yon="ALIS", ad="ALIŞ FATURASI-GİDER").update(gider=True)


def gider_isaretini_kaldir(apps, schema_editor):
    apps.get_model("core", "FaturaTipi").objects.filter(gider=True).update(gider=False)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_ozel_depo_cari_aday_cek'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='faturasatir',
            name='hesap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fatura_satirlari', to='core.hesapplani', verbose_name='gider hesabı'),
        ),
        migrations.AddField(
            model_name='faturatipi',
            name='gider',
            field=models.BooleanField(default=False, verbose_name='gider faturası'),
        ),
        migrations.AlterField(
            model_name='faturasatir',
            name='stok',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fatura_satirlari', to='core.stok', verbose_name='stok'),
        ),
        migrations.AddConstraint(
            model_name='faturasatir',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('hesap__isnull', True), ('stok__isnull', False)), models.Q(('hesap__isnull', False), ('stok__isnull', True)), _connector='OR'), name='ck_fatura_satir_stok_veya_hesap'),
        ),
        migrations.RunPython(gider_tipini_isaretle, gider_isaretini_kaldir),
    ]
