# Generated by Django 6.0.5 on 2026-09-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_gider_alt_hesaplari'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaymusteri',
            name='asama',
            field=models.CharField(choices=[('YENI', 'Yeni'), ('TEMAS', 'Temas kuruldu'), ('ILGILI', 'İlgileniyor'), ('TEKLIF', 'Teklif verildi'), ('NUMUNE', 'Numune'), ('SIPARIS', 'Sipariş'), ('KAPALI', 'Kapalı')], db_index=True, default='YENI', max_length=10, verbose_name='aşama'),
        ),
        migrations.AddField(
            model_name='adaymusteri',
            name='kapanis_nedeni',
            field=models.CharField(blank=True, choices=[('ULASILAMIYOR', 'Ulaşılamıyor'), ('ILGISIZ', 'İlgilenmiyor'), ('RAKIP', 'Rakiple çalışıyor'), ('KAPANMIS', 'Firma kapanmış'), ('DIGER', 'Diğer')], default='', max_length=20, verbose_name='kapanış nedeni'),
        ),
        migrations.AddField(
            model_name='adaymusteri',
            name='potansiyel',
            field=models.CharField(blank=True, choices=[('DUSUK', 'Düşük'), ('ORTA', 'Orta'), ('YUKSEK', 'Yüksek')], db_index=True, default='', max_length=10, verbose_name='potansiyel'),
        ),
        migrations.AddField(
            model_name='adaymusteri',
            name='tip',
            field=models.CharField(choices=[('ESKI_MUSTERI', 'Eski müşteri (Çakmak)'), ('ADAY', 'Aday'), ('ARACI', 'Aracı / Komisyoncu'), ('LOJISTIK', 'Lojistik / Nakliye'), ('GUMRUK', 'Gümrük müşaviri'), ('TEDARIKCI', 'Tedarikçi'), ('RAKIP', 'Rakip'), ('PAZAR_BILGISI', 'Pazar bilgisi (firma değil)')], db_index=True, default='ADAY', max_length=20, verbose_name='tip'),
        ),
    ]
