# Generated by Django 6.0.5 on 2026-09-27 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0126_aday_musteri_tip_veri_tasima'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaymusteri',
            name='eposta_2_gecersiz',
            field=models.BooleanField(default=False, verbose_name='e-posta 2 geçersiz (bounce)'),
        ),
        migrations.AddField(
            model_name='adaymusteri',
            name='eposta_gecersiz',
            field=models.BooleanField(default=False, verbose_name='e-posta geçersiz (bounce)'),
        ),
        migrations.AddField(
            model_name='adaymusteri',
            name='sonraki_adim',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='sonraki adım'),
        ),
        migrations.AddField(
            model_name='adaymusteri',
            name='sonraki_adim_tarihi',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='sonraki adım tarihi'),
        ),
    ]
