# Generated by Django 6.0.5 on 2026-09-27 01:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0127_aday_musteri_takip_eposta_gecersiz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='adayaktivite',
            index=models.Index(fields=['aday', '-tarih'], name='ix_aday_aktivite_aday_tarih'),
        ),
    ]
