# Generated by Django 6.0.5 on 2026-09-27 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0128_aday_aktivite_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adaymusteri',
            name='adres',
            field=models.TextField(blank=True, default='', verbose_name='adres'),
        ),
        migrations.AddField(
            model_name='adaymusteri',
            name='telefon_2_whatsapp',
            field=models.BooleanField(default=False, verbose_name='bu numara WhatsApp kullanıyor'),
        ),
        migrations.AddField(
            model_name='adaymusteri',
            name='telefon_whatsapp',
            field=models.BooleanField(default=False, verbose_name='bu numara WhatsApp kullanıyor'),
        ),
        migrations.AddField(
            model_name='adaymusteri',
            name='web',
            field=models.URLField(blank=True, default='', verbose_name='web'),
        ),
        migrations.AddField(
            model_name='cari',
            name='telefon_2_whatsapp',
            field=models.BooleanField(default=False, verbose_name='bu numara WhatsApp kullanıyor'),
        ),
        migrations.AddField(
            model_name='cari',
            name='telefon_whatsapp',
            field=models.BooleanField(default=False, verbose_name='bu numara WhatsApp kullanıyor'),
        ),
        migrations.AddField(
            model_name='cariyetkili',
            name='whatsapp',
            field=models.BooleanField(default=False, verbose_name='bu numara WhatsApp kullanıyor'),
        ),
        migrations.AlterField(
            model_name='adayaktivite',
            name='tur',
            field=models.CharField(choices=[('GORUSME', 'Görüşme'), ('TELEFON', 'Telefon'), ('TOPLANTI', 'Toplantı'), ('EPOSTA', 'E-posta'), ('WHATSAPP', 'WhatsApp'), ('NOT', 'Not')], default='NOT', max_length=10, verbose_name='tür'),
        ),
        migrations.AlterField(
            model_name='cariaktivite',
            name='tur',
            field=models.CharField(choices=[('GORUSME', 'Görüşme'), ('TELEFON', 'Telefon'), ('TOPLANTI', 'Toplantı'), ('EPOSTA', 'E-posta'), ('WHATSAPP', 'WhatsApp'), ('NOT', 'Not')], default='NOT', max_length=10, verbose_name='tür'),
        ),
        migrations.CreateModel(
            name='AdayYetkili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('ad_soyad', models.CharField(max_length=120, verbose_name='ad soyad')),
                ('unvan', models.CharField(blank=True, max_length=80, verbose_name='görev/unvan')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='telefon')),
                ('eposta', models.EmailField(blank=True, max_length=254, verbose_name='e-posta')),
                ('notlar', models.CharField(blank=True, max_length=200, verbose_name='notlar')),
                ('whatsapp', models.BooleanField(default=False, verbose_name='bu numara WhatsApp kullanıyor')),
                ('aday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yetkililer', to='core.adaymusteri', verbose_name='aday')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'yetkili kişi',
                'verbose_name_plural': 'yetkili kişiler',
                'db_table': 'aday_yetkili',
                'ordering': ['ad_soyad'],
            },
        ),
    ]
