# Generated by Django 6.0.5 on 2026-09-27 09:39

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0129_aday_yetkili_whatsapp_web_adres'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='adayaktivite',
            index=django.contrib.postgres.indexes.GinIndex(fields=['aciklama'], name='gin_aday_akt_aciklama', opclasses=['gin_trgm_ops']),
        ),
    ]
