# Generated by Django 6.0.5 on 2026-09-27 09:57 (elle düzenlendi: veri taşıma eklendi)
"""AdayMusteri.donusen_cari -> cari + cariye_donusum_tarihi (Cariye Dönüştür yeniden
yazılıyor, bkz. core.services.aday_donustur). Canlıda tek satır etkilenir (aday #64 ->
cari #35, bkz. rapor); cariye_donusum_tarihi o satır için NULL kalır — geçmiş dönüşüm
zamanı hiçbir yerde tutulmuyordu, uydurma bir tarih yazılmaz."""

import django.db.models.deletion
from django.db import migrations, models


def _donusen_cariyi_tasi(apps, schema_editor):
    AdayMusteri = apps.get_model("core", "AdayMusteri")
    AdayMusteri.objects.filter(donusen_cari__isnull=False).update(cari=models.F("donusen_cari"))


def _geri_al(apps, schema_editor):
    AdayMusteri = apps.get_model("core", "AdayMusteri")
    AdayMusteri.objects.filter(cari__isnull=False).update(donusen_cari=models.F("cari"))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0130_aday_aktivite_gin_aciklama'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaymusteri',
            name='cari',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kaynak_adaylar', to='core.cari', verbose_name='cari'),
        ),
        migrations.AddField(
            model_name='adaymusteri',
            name='cariye_donusum_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='cariye dönüşüm tarihi'),
        ),
        migrations.RunPython(_donusen_cariyi_tasi, _geri_al),
        migrations.RemoveField(
            model_name='adaymusteri',
            name='donusen_cari',
        ),
    ]
