# Generated by Django 6.0.5 on 2026-09-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0136_aday_cari_telefon_normalize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adayasamatanim',
            name='rol',
            field=models.CharField(choices=[('BASLANGIC', 'Başlangıç'), ('ARA', 'Ara'), ('KAPALI', 'Kapalı'), ('CARI', 'Cari olunca')], default='ARA', max_length=10, verbose_name='rol'),
        ),
    ]
