# Generated by Django 6.0.5 on 2026-09-27 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_cari_donusum_asama_seed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonelUcret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('gecerlilik_baslangic', models.DateField(verbose_name='geçerlilik başlangıcı')),
                ('tip', models.CharField(choices=[('ASGARI', 'Asgari Ücret'), ('NET', 'Net Ücret')], max_length=10, verbose_name='tip')),
                ('net_tutar', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='net tutar (TL)')),
                ('aciklama', models.CharField(blank=True, max_length=200, verbose_name='açıklama')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ucretler', to='core.personel', verbose_name='personel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'personel ücreti',
                'verbose_name_plural': 'personel ücretleri',
                'db_table': 'core_personel_ucret',
                'ordering': ['-gecerlilik_baslangic', '-id'],
                'indexes': [models.Index(fields=['personel', 'gecerlilik_baslangic'], name='ix_personel_ucret_kisi_bas')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('silindi', False)), fields=('personel', 'gecerlilik_baslangic'), name='uq_personel_ucret_kisi_bas_aktif'), models.CheckConstraint(condition=models.Q(models.Q(('net_tutar__isnull', True), ('tip', 'ASGARI')), models.Q(('net_tutar__gt', 0), ('net_tutar__isnull', False), ('tip', 'NET')), _connector='OR'), name='ck_personel_ucret_tip_tutar')],
            },
        ),
    ]
