# Generated by Django 6.0.5 on 2026-09-28 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0141_resmi_tatil_seed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='kullanici',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personel_karti', to=settings.AUTH_USER_MODEL, verbose_name='mesai hesabı'),
        ),
        migrations.CreateModel(
            name='MesaiIzinliAg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('cidr', models.CharField(max_length=43, verbose_name='IP / CIDR')),
                ('aciklama', models.CharField(blank=True, max_length=100, verbose_name='açıklama')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'mesai izinli ağı',
                'verbose_name_plural': 'mesai izinli ağları',
                'db_table': 'core_mesai_izinli_ag',
                'ordering': ['cidr'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('silindi', False)), fields=('cidr',), name='uq_mesai_izinli_ag_aktif')],
            },
        ),
        migrations.CreateModel(
            name='MesaiKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('is_tarihi', models.DateField(verbose_name='iş tarihi')),
                ('giris_zamani', models.DateTimeField(verbose_name='giriş zamanı')),
                ('cikis_zamani', models.DateTimeField(blank=True, null=True, verbose_name='çıkış zamanı')),
                ('giris_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='giriş IP')),
                ('cikis_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='çıkış IP')),
                ('kaynak', models.CharField(choices=[('PERSONEL', 'Personel'), ('YONETICI', 'Yönetici')], default='PERSONEL', max_length=10, verbose_name='kaynak')),
                ('duzeltme_notu', models.CharField(blank=True, max_length=300, verbose_name='düzeltme notu')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mesai_kayitlari', to='core.personel', verbose_name='personel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'mesai kaydı',
                'verbose_name_plural': 'mesai kayıtları',
                'db_table': 'core_mesai_kaydi',
                'ordering': ['-giris_zamani', '-id'],
                'indexes': [models.Index(fields=['personel', 'is_tarihi'], name='ix_mesai_kaydi_kisi_gun')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('cikis_zamani__isnull', True), ('silindi', False)), fields=('personel', 'is_tarihi'), name='uq_mesai_acik_kayit'), models.CheckConstraint(condition=models.Q(('cikis_zamani__isnull', True), ('cikis_zamani__gte', models.F('giris_zamani')), _connector='OR'), name='ck_mesai_cikis_gte_giris')],
            },
        ),
    ]
