# Generated by Django 6.0.5 on 2026-10-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0144_yukleme_sekli_kod_onek'),
    ]

    operations = [
        migrations.AddField(
            model_name='teklifsiparis',
            name='red_nedeni',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='red nedeni'),
        ),
        migrations.AlterField(
            model_name='adayasamatanim',
            name='rol',
            field=models.CharField(choices=[('BASLANGIC', 'Başlangıç'), ('ARA', 'Ara'), ('KAPALI', 'Kapalı'), ('CARI', 'Cari olunca'), ('TEKLIF', 'Teklif verilince'), ('SIPARIS', 'Sipariş olunca')], default='ARA', max_length=10, verbose_name='rol'),
        ),
        migrations.AlterField(
            model_name='teklifsiparis',
            name='durum',
            field=models.CharField(choices=[('TASLAK', 'Taslak'), ('ONAYLI', 'Onaylı'), ('GONDERILDI', 'Gönderildi'), ('KABUL', 'Kabul Edildi'), ('RED', 'Reddedildi'), ('SURESI_DOLDU', 'Süresi Doldu'), ('IPTAL', 'İptal Edildi')], default='TASLAK', max_length=12, verbose_name='durum'),
        ),
    ]
