# Generated by Django 6.0.5 on 2026-10-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0148_fatura_vade_tarihi'),
    ]

    operations = [
        migrations.AddField(
            model_name='cari',
            name='odeme_gunu',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ödeme günü'),
        ),
        migrations.AddField(
            model_name='cari',
            name='odeme_kosulu',
            field=models.CharField(blank=True, choices=[('PESIN', 'Peşin (fatura tarihi)'), ('GUN_SONRA', 'Fatura tarihinden X gün sonra'), ('SONRAKI_AY_GUNU', 'Sonraki ayın N. günü')], max_length=20, null=True, verbose_name='ödeme koşulu'),
        ),
    ]
