# Generated by Django 6.0.5 on 2026-10-02 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0149_cari_odeme_kosulu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YatirimProjesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('kod', models.CharField(max_length=20, verbose_name='proje kodu')),
                ('ad', models.CharField(max_length=200, verbose_name='ad')),
                ('aciklama', models.TextField(blank=True, verbose_name='açıklama')),
                ('durum', models.CharField(choices=[('DEVAM', 'Devam Ediyor'), ('AKTIFLESTI', 'Aktifleşti')], default='DEVAM', max_length=12, verbose_name='durum')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'yatırım projesi',
                'verbose_name_plural': 'yatırım projeleri',
                'db_table': 'yatirim_projesi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='faturasatir',
            name='yatirim_projesi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fatura_satirlari', to='core.yatirimprojesi', verbose_name='yatırım projesi'),
        ),
        migrations.AddConstraint(
            model_name='yatirimprojesi',
            constraint=models.UniqueConstraint(condition=models.Q(('silindi', False)), fields=('kod',), name='uq_yatirim_projesi_kod_aktif'),
        ),
    ]
