# Generated by Django 6.0.5 on 2026-10-03 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0150_yatirim_projesi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DuranVarlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('demirbas_kodu', models.CharField(max_length=20, verbose_name='demirbaş kodu')),
                ('ad', models.CharField(max_length=200, verbose_name='ad')),
                ('aktiflestirme_tarihi', models.DateField(verbose_name='aktifleştirme tarihi')),
                ('maliyet', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='maliyet (KDV hariç, TRY)')),
                ('marka_model', models.CharField(blank=True, max_length=200, verbose_name='marka / model')),
                ('seri_no', models.CharField(blank=True, max_length=100, verbose_name='seri no')),
                ('durum', models.CharField(choices=[('AKTIF', 'Aktif'), ('PASIF', 'Pasif')], default='AKTIF', max_length=10, verbose_name='durum')),
                ('notlar', models.TextField(blank=True, verbose_name='notlar')),
                ('kaynak', models.CharField(choices=[('FATURA', 'Fatura'), ('PROJE', 'Yatırım Projesi'), ('ACILIS', 'Açılış')], max_length=10, verbose_name='kaynak')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('fatura_satirlari', models.ManyToManyField(blank=True, related_name='duran_varliklar', to='core.faturasatir', verbose_name='fatura kalemleri')),
                ('hesap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duran_varliklar', to='core.hesapplani', verbose_name='muhasebe hesabı')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
                ('yatirim_projesi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duran_varliklar', to='core.yatirimprojesi', verbose_name='yatırım projesi')),
            ],
            options={
                'verbose_name': 'duran varlık',
                'verbose_name_plural': 'duran varlıklar',
                'db_table': 'duran_varlik',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('silindi', False)), fields=('demirbas_kodu',), name='uq_duran_varlik_kod_aktif'), models.CheckConstraint(condition=models.Q(('maliyet__gte', 0)), name='ck_duran_varlik_maliyet_gte0')],
            },
        ),
    ]
