# Generated by Django 6.0.5 on 2026-10-03 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0151_duran_varlik'),
    ]

    operations = [
        migrations.AddField(
            model_name='yatirimprojesi',
            name='aktiflestirme_fisi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='yatirim_projesi_aktiflestirmeleri', to='core.yevmiyefisi', verbose_name='aktifleştirme fişi'),
        ),
        migrations.AlterField(
            model_name='yevmiyefisi',
            name='kaynak',
            field=models.CharField(choices=[('MANUEL', 'Manuel'), ('FATURA', 'Fatura (otomatik)'), ('KASA', 'Kasa Hareketi (otomatik)'), ('BANKA', 'Banka Hareketi (otomatik)'), ('CEK_SENET', 'Çek/Senet Bordrosu (otomatik)'), ('KREDI_KARTI', 'Kredi Kartı Hareketi (otomatik)'), ('KREDI', 'Kredi Hareketi (otomatik)'), ('YATIRIM', 'Yatırım Projesi Aktifleştirme (otomatik)')], default='MANUEL', max_length=20, verbose_name='kaynak'),
        ),
    ]
