# Generated by Django 6.0.5 on 2026-10-03 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0152_yatirim_projesi_aktiflestirme'),
    ]

    operations = [
        migrations.AddField(
            model_name='stokhareket',
            name='fis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stok_sarf_hareketleri', to='core.yevmiyefisi', verbose_name='muhasebe fişi'),
        ),
        migrations.AddField(
            model_name='stokhareket',
            name='karsi_hesap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stok_sarf_hareketleri', to='core.hesapplani', verbose_name='karşı hesap'),
        ),
        migrations.AddField(
            model_name='stokhareket',
            name='yatirim_projesi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stok_sarf_hareketleri', to='core.yatirimprojesi', verbose_name='yatırım projesi'),
        ),
        migrations.AlterField(
            model_name='stokhareket',
            name='kaynak',
            field=models.CharField(choices=[('MANUEL', 'Manuel'), ('FATURA', 'Fatura'), ('IRSALIYE', 'İrsaliye'), ('URETIM', 'Üretim'), ('SARF', 'Sarf (hesaba çıkış)')], default='MANUEL', max_length=20, verbose_name='kaynak'),
        ),
        migrations.AlterField(
            model_name='yevmiyefisi',
            name='kaynak',
            field=models.CharField(choices=[('MANUEL', 'Manuel'), ('FATURA', 'Fatura (otomatik)'), ('KASA', 'Kasa Hareketi (otomatik)'), ('BANKA', 'Banka Hareketi (otomatik)'), ('CEK_SENET', 'Çek/Senet Bordrosu (otomatik)'), ('KREDI_KARTI', 'Kredi Kartı Hareketi (otomatik)'), ('KREDI', 'Kredi Hareketi (otomatik)'), ('YATIRIM', 'Yatırım Projesi Aktifleştirme (otomatik)'), ('STOK_SARF', 'Stok Sarf Çıkışı (otomatik)')], default='MANUEL', max_length=20, verbose_name='kaynak'),
        ),
    ]
