# Generated by Django 6.0.5 on 2026-10-03 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0153_stokhareket_fis_stokhareket_karsi_hesap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yevmiyesatir',
            name='yatirim_projesi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='yevmiye_satirlari', to='core.yatirimprojesi', verbose_name='yatırım projesi'),
        ),
    ]
