# Generated by Django 6.0.5 on 2026-10-03 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0154_yevmiyesatir_yatirim_projesi'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='sahsi_alis',
            field=models.BooleanField(default=False, verbose_name='ortak adına (şahsi) alış'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='sahsi_ortak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sahsi_alis_faturalari', to='core.hesapplani', verbose_name='ortak hesabı'),
        ),
    ]
