# Generated by Django 6.0.5 on 2026-10-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0155_fatura_sahsi_alis_fatura_sahsi_ortak'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='gv_stopaj_orani',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='GV stopaj oranı (%)'),
        ),
        migrations.AddField(
            model_name='faturatipi',
            name='stopajli',
            field=models.BooleanField(default=False, verbose_name='GV stopajlı (serbest meslek makbuzu)'),
        ),
    ]
