# Generated by Django 6.0.5 on 2026-10-03 18:20

import core.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0156_fatura_gv_stopaj_orani_faturatipi_stopajli'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaturaEk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('dosya', models.FileField(storage=core.storage.ozel_depo, upload_to=core.storage.fatura_ek_yolu, verbose_name='dosya')),
                ('orijinal_ad', models.CharField(blank=True, max_length=255, verbose_name='orijinal dosya adı')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ekler', to='core.fatura', verbose_name='fatura')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'fatura eki',
                'verbose_name_plural': 'fatura ekleri',
                'db_table': 'fatura_ek',
                'ordering': ['id'],
            },
        ),
    ]
