# Generated by Django 6.0.5 on 2026-10-03 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0157_fatura_ek'),
    ]

    operations = [
        migrations.AddField(
            model_name='stok',
            name='maliyet_deger_try',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='stok değeri TL (önbellek)'),
        ),
        migrations.AddField(
            model_name='stok',
            name='maliyet_deger_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='stok değeri USD (önbellek)'),
        ),
        migrations.AddField(
            model_name='stok',
            name='maliyet_miktar',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='maliyet miktarı (önbellek)'),
        ),
        migrations.AddField(
            model_name='stok',
            name='ort_maliyet_try',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='ortalama maliyet TL (önbellek)'),
        ),
        migrations.AddField(
            model_name='stok',
            name='ort_maliyet_usd',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='ortalama maliyet USD (önbellek)'),
        ),
        migrations.AddField(
            model_name='stokhareket',
            name='birim_maliyet_try',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='birim maliyet TL'),
        ),
        migrations.AddField(
            model_name='stokhareket',
            name='birim_maliyet_usd',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='birim maliyet USD'),
        ),
        migrations.AddField(
            model_name='stokhareket',
            name='giris_tahmini',
            field=models.BooleanField(default=False, verbose_name='giriş tutarı tahmini'),
        ),
        migrations.AddField(
            model_name='stokhareket',
            name='giris_tutar_try',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='giriş tutarı TL (fatura)'),
        ),
        migrations.AddField(
            model_name='stokhareket',
            name='giris_tutar_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='giriş tutarı USD (fatura)'),
        ),
        migrations.AddField(
            model_name='stokhareket',
            name='maliyet_durumu',
            field=models.CharField(choices=[('KESIN', 'Kesin'), ('GECICI', 'Geçici'), ('YOK', 'Maliyetsiz')], default='YOK', max_length=6, verbose_name='maliyet durumu'),
        ),
        migrations.AddField(
            model_name='stokhareket',
            name='maliyet_fatura_satir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maliyet_hareketleri', to='core.faturasatir', verbose_name='maliyeti belirleyen fatura satırı'),
        ),
        migrations.AddField(
            model_name='stokhareket',
            name='sonrasi_deger_try',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='hareket sonrası değer TL'),
        ),
        migrations.AddField(
            model_name='stokhareket',
            name='sonrasi_deger_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='hareket sonrası değer USD'),
        ),
        migrations.AddField(
            model_name='stokhareket',
            name='sonrasi_miktar',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='hareket sonrası miktar'),
        ),
        migrations.AddField(
            model_name='stokhareket',
            name='sonrasi_ort_try',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='hareket sonrası ortalama TL'),
        ),
        migrations.AddField(
            model_name='stokhareket',
            name='sonrasi_ort_usd',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='hareket sonrası ortalama USD'),
        ),
        migrations.AddField(
            model_name='stokhareket',
            name='tutar_try',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='değer TL'),
        ),
        migrations.AddField(
            model_name='stokhareket',
            name='tutar_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='değer USD'),
        ),
    ]
