# Generated by Django 6.0.5 on 2026-10-03 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0158_stok_ortalama_maliyet'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturatipi',
            name='maliyet_fisi',
            field=models.CharField(blank=True, choices=[('', 'Maliyet fişi yok'), ('SATIS', 'Satış (çıkış maliyeti: 620/621/623 borç, stok alacak)'), ('SATIS_IADE', 'Satış iadesi (giriş ortalamadan, ters maliyet fişi)')], default='', max_length=10, verbose_name='stok maliyet fişi'),
        ),
        migrations.AddField(
            model_name='operasyonkaydi',
            name='fis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operasyon_kayitlari', to='core.yevmiyefisi', verbose_name='maliyet aktarım fişi'),
        ),
        migrations.AddField(
            model_name='stokhareket',
            name='giris_ortalama',
            field=models.BooleanField(default=False, verbose_name='giriş ortalamadan değerlenir'),
        ),
        migrations.AddField(
            model_name='stokhareket',
            name='operasyon_kaydi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stok_hareketleri_maliyet', to='core.operasyonkaydi', verbose_name='operasyon kaydı'),
        ),
        migrations.AddField(
            model_name='stokhareket',
            name='transfer_grubu',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='transfer grubu'),
        ),
        migrations.AlterField(
            model_name='stokhareket',
            name='kaynak',
            field=models.CharField(choices=[('MANUEL', 'Manuel'), ('FATURA', 'Fatura'), ('IRSALIYE', 'İrsaliye'), ('URETIM', 'Üretim'), ('SARF', 'Sarf (hesaba çıkış)'), ('TRANSFER', 'Depo transferi')], default='MANUEL', max_length=20, verbose_name='kaynak'),
        ),
        migrations.AlterField(
            model_name='yevmiyefisi',
            name='kaynak',
            field=models.CharField(choices=[('MANUEL', 'Manuel'), ('FATURA', 'Fatura (otomatik)'), ('KASA', 'Kasa Hareketi (otomatik)'), ('BANKA', 'Banka Hareketi (otomatik)'), ('CEK_SENET', 'Çek/Senet Bordrosu (otomatik)'), ('KREDI_KARTI', 'Kredi Kartı Hareketi (otomatik)'), ('KREDI', 'Kredi Hareketi (otomatik)'), ('YATIRIM', 'Yatırım Projesi Aktifleştirme (otomatik)'), ('STOK_SARF', 'Stok Sarf Çıkışı (otomatik)'), ('URETIM', 'Üretim Maliyet Aktarımı (otomatik)'), ('STOK_SATIS', 'Satış Maliyeti (otomatik)')], default='MANUEL', max_length=20, verbose_name='kaynak'),
        ),
    ]
