# Generated by Django 6.0.5 on 2026-10-03 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0159_stok_maliyet_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='taslak_kur',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='taslakta girilen kur'),
        ),
    ]
