# Generated by Django 6.0.5 on 2026-10-04 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0160_fatura_taslak_kur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FisNoSayaci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil', models.IntegerField(unique=True, verbose_name='mali yıl')),
                ('son_no', models.PositiveIntegerField(default=0, verbose_name='son verilen fiş no')),
            ],
            options={
                'verbose_name': 'fiş no sayacı',
                'verbose_name_plural': 'fiş no sayaçları',
                'db_table': 'yevmiye_fis_no_sayaci',
            },
        ),
        migrations.CreateModel(
            name='SilmeKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('tur', models.CharField(choices=[('FIS', 'Yevmiye fişi'), ('CEK_BORDRO', 'Çek/senet bordrosu')], max_length=12, verbose_name='tür')),
                ('kayit_no', models.CharField(max_length=40, verbose_name='kayıt no')),
                ('tarih', models.DateField(blank=True, null=True, verbose_name='kayıt tarihi')),
                ('tutar', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='tutar (TL)')),
                ('aciklama', models.CharField(blank=True, max_length=500, verbose_name='açıklama')),
                ('kaynak', models.CharField(blank=True, max_length=20, verbose_name='kaynak')),
                ('veri', models.JSONField(default=dict, verbose_name='silinen veri')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('silen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='silen')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'silme kaydı',
                'verbose_name_plural': 'silme kayıtları',
                'db_table': 'silme_kaydi',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
