# Generated by Django 6.0.5 on 2026-10-04 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0161_silme_kaydi_fis_no_sayaci'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='yevmiyesatir',
            name='ana_satir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kur_farki_satirlari', to='core.yevmiyesatir', verbose_name='kur farkının ana satırı'),
        ),
        migrations.AddField(
            model_name='yevmiyesatir',
            name='ham_tl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='ham TL (işlem kuruyla)'),
        ),
        migrations.AddField(
            model_name='yevmiyesatir',
            name='ort_kur',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='kullanılan ortalama kur'),
        ),
        migrations.AlterField(
            model_name='yevmiyefisi',
            name='kaynak',
            field=models.CharField(choices=[('MANUEL', 'Manuel'), ('FATURA', 'Fatura (otomatik)'), ('KASA', 'Kasa Hareketi (otomatik)'), ('BANKA', 'Banka Hareketi (otomatik)'), ('CEK_SENET', 'Çek/Senet Bordrosu (otomatik)'), ('KREDI_KARTI', 'Kredi Kartı Hareketi (otomatik)'), ('KREDI', 'Kredi Hareketi (otomatik)'), ('YATIRIM', 'Yatırım Projesi Aktifleştirme (otomatik)'), ('STOK_SARF', 'Stok Sarf Çıkışı (otomatik)'), ('URETIM', 'Üretim Maliyet Aktarımı (otomatik)'), ('STOK_SATIS', 'Satış Maliyeti (otomatik)'), ('KUR_DEGERLEME', 'Dönem Sonu Kur Değerleme')], default='MANUEL', max_length=20, verbose_name='kaynak'),
        ),
        migrations.CreateModel(
            name='KurDegerleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('tarih', models.DateField(verbose_name='değerleme tarihi')),
                ('toplam_kar', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='kambiyo kârı (TL)')),
                ('toplam_zarar', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='kambiyo zararı (TL)')),
                ('kurlar', models.JSONField(default=dict, verbose_name='kullanılan kurlar')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('fis', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='kur_degerleme', to='core.yevmiyefisi', verbose_name='değerleme fişi')),
                ('ters_fis', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kur_degerleme_ters', to='core.yevmiyefisi', verbose_name='ters kayıt fişi')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'kur değerleme',
                'verbose_name_plural': 'kur değerlemeleri',
                'db_table': 'kur_degerleme',
                'ordering': ['-tarih', '-id'],
            },
        ),
    ]
