# Generated by Django 6.0.5 on 2026-10-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0162_kur_farki_motoru'),
    ]

    operations = [
        migrations.AddField(
            model_name='cari',
            name='kur_degerleme',
            field=models.CharField(choices=[('OTOMATIK', 'Otomatik (avans değerlenmez)'), ('HER_ZAMAN', 'Her zaman değerle'), ('HIC', 'Hiç değerleme')], default='OTOMATIK', max_length=10, verbose_name='kur değerlemesi'),
        ),
    ]
