# Generated by Django 6.0.5 on 2026-10-04 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0164_ocean_kur_ayarlari'),
    ]

    operations = [
        migrations.AddField(
            model_name='duranvarlik',
            name='birikmis_amortisman',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='birikmiş amortisman (TRY)'),
        ),
        migrations.AddField(
            model_name='duranvarlik',
            name='satis_faturasi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='satilan_demirbaslar', to='core.fatura', verbose_name='satış faturası'),
        ),
        migrations.AddField(
            model_name='duranvarlik',
            name='satis_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='satış tarihi'),
        ),
        migrations.AddField(
            model_name='faturasatir',
            name='demirbas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='satis_satirlari', to='core.duranvarlik', verbose_name='satılan demirbaş'),
        ),
        migrations.AddField(
            model_name='yevmiyefisi',
            name='cari',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kesinti_fisleri', to='core.cari', verbose_name='kaynak cari'),
        ),
        migrations.AlterField(
            model_name='duranvarlik',
            name='durum',
            field=models.CharField(choices=[('AKTIF', 'Aktif'), ('PASIF', 'Pasif'), ('SATILDI', 'Satıldı')], default='AKTIF', max_length=10, verbose_name='durum'),
        ),
        migrations.AlterField(
            model_name='yevmiyefisi',
            name='kaynak',
            field=models.CharField(choices=[('MANUEL', 'Manuel'), ('FATURA', 'Fatura (otomatik)'), ('KASA', 'Kasa Hareketi (otomatik)'), ('BANKA', 'Banka Hareketi (otomatik)'), ('CEK_SENET', 'Çek/Senet Bordrosu (otomatik)'), ('KREDI_KARTI', 'Kredi Kartı Hareketi (otomatik)'), ('KREDI', 'Kredi Hareketi (otomatik)'), ('YATIRIM', 'Yatırım Projesi Aktifleştirme (otomatik)'), ('STOK_SARF', 'Stok Sarf Çıkışı (otomatik)'), ('URETIM', 'Üretim Maliyet Aktarımı (otomatik)'), ('STOK_SATIS', 'Satış Maliyeti (otomatik)'), ('KUR_DEGERLEME', 'Dönem Sonu Kur Değerleme'), ('CARI_KESINTI', 'Cari Kesinti / Masraf (otomatik)')], default='MANUEL', max_length=20, verbose_name='kaynak'),
        ),
    ]
