# Generated by Django 6.0.5 on 2026-10-04 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0165_satis_hesap_demirbas_kesinti'),
    ]

    operations = [
        migrations.AddField(
            model_name='yatirimprojesi',
            name='hesap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='yatirim_projeleri', to='core.hesapplani', verbose_name='muhasebe hesabı'),
        ),
    ]
