# Generated by Django 6.0.5 on 2026-10-04 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0166_yatirim_projesi_hesap'),
    ]

    operations = [
        migrations.AddField(
            model_name='duranvarlik',
            name='fis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duran_varlik_acilislari', to='core.yevmiyefisi', verbose_name='açılış fişi'),
        ),
        migrations.AddField(
            model_name='duranvarlik',
            name='karsi_hesap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duran_varlik_karsi_kartlar', to='core.hesapplani', verbose_name='karşı hesap'),
        ),
        migrations.AlterField(
            model_name='yevmiyefisi',
            name='kaynak',
            field=models.CharField(choices=[('MANUEL', 'Manuel'), ('FATURA', 'Fatura (otomatik)'), ('KASA', 'Kasa Hareketi (otomatik)'), ('BANKA', 'Banka Hareketi (otomatik)'), ('CEK_SENET', 'Çek/Senet Bordrosu (otomatik)'), ('KREDI_KARTI', 'Kredi Kartı Hareketi (otomatik)'), ('KREDI', 'Kredi Hareketi (otomatik)'), ('YATIRIM', 'Yatırım Projesi Aktifleştirme (otomatik)'), ('STOK_SARF', 'Stok Sarf Çıkışı (otomatik)'), ('URETIM', 'Üretim Maliyet Aktarımı (otomatik)'), ('STOK_SATIS', 'Satış Maliyeti (otomatik)'), ('KUR_DEGERLEME', 'Dönem Sonu Kur Değerleme'), ('CARI_KESINTI', 'Cari Kesinti / Masraf (otomatik)'), ('DURAN_VARLIK', 'Duran Varlık Kartı Açılışı (otomatik)')], default='MANUEL', max_length=20, verbose_name='kaynak'),
        ),
    ]
