# Generated by Django 6.0.5 on 2026-10-04 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0167_duran_varlik_karsi_hesap'),
    ]

    operations = [
        migrations.AddField(
            model_name='cekhesapayari',
            name='doviz_cari_ara',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.hesapplani', verbose_name='döviz carilere verilen çekler ara hesabı'),
        ),
        migrations.AddField(
            model_name='ceksenet',
            name='ara_hesapta',
            field=models.BooleanField(default=False, verbose_name='ara hesapta bekliyor'),
        ),
    ]
