# Generated by Django 6.0.5 on 2026-10-04 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0168_doviz_cari_cek_ara_hesap'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='faturasatir',
            name='donem_aciklama',
            field=models.CharField(blank=True, max_length=200, verbose_name='dönemsel gider açıklaması'),
        ),
        migrations.AddField(
            model_name='faturasatir',
            name='donem_baslangic',
            field=models.DateField(blank=True, null=True, verbose_name='dönem başlangıcı'),
        ),
        migrations.AddField(
            model_name='faturasatir',
            name='donem_bitis',
            field=models.DateField(blank=True, null=True, verbose_name='dönem bitişi'),
        ),
        migrations.AddField(
            model_name='faturasatir',
            name='donem_gider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donemsel_satirlar', to='core.hesapplani', verbose_name='dönemsel gider hesabı'),
        ),
        migrations.AlterField(
            model_name='yevmiyefisi',
            name='kaynak',
            field=models.CharField(choices=[('MANUEL', 'Manuel'), ('FATURA', 'Fatura (otomatik)'), ('KASA', 'Kasa Hareketi (otomatik)'), ('BANKA', 'Banka Hareketi (otomatik)'), ('CEK_SENET', 'Çek/Senet Bordrosu (otomatik)'), ('KREDI_KARTI', 'Kredi Kartı Hareketi (otomatik)'), ('KREDI', 'Kredi Hareketi (otomatik)'), ('YATIRIM', 'Yatırım Projesi Aktifleştirme (otomatik)'), ('STOK_SARF', 'Stok Sarf Çıkışı (otomatik)'), ('URETIM', 'Üretim Maliyet Aktarımı (otomatik)'), ('STOK_SATIS', 'Satış Maliyeti (otomatik)'), ('KUR_DEGERLEME', 'Dönem Sonu Kur Değerleme'), ('CARI_KESINTI', 'Cari Kesinti / Masraf (otomatik)'), ('DURAN_VARLIK', 'Duran Varlık Kartı Açılışı (otomatik)'), ('DONEMSEL', 'Dönemsel Dağıtım (otomatik)')], default='MANUEL', max_length=20, verbose_name='kaynak'),
        ),
        migrations.CreateModel(
            name='DonemselDagitim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('sira', models.PositiveIntegerField(verbose_name='sıra')),
                ('ay_sonu', models.DateField(verbose_name='ay sonu')),
                ('doviz', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='tutar (fatura para birimi)')),
                ('para_birimi', models.CharField(max_length=3, verbose_name='para birimi')),
                ('kur', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='kur')),
                ('tl', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='TL karşılığı')),
                ('aciklama', models.CharField(blank=True, max_length=200, verbose_name='açıklama')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donemsel_dagitimlar', to='core.fatura', verbose_name='fatura')),
                ('fis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donemsel_dagitimlari', to='core.yevmiyefisi', verbose_name='dağıtım fişi')),
                ('gider_hesap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.hesapplani', verbose_name='gider hesabı')),
                ('hesap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donemsel_dagitimlar', to='core.hesapplani', verbose_name='180 hesabı')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'dönemsel dağıtım',
                'verbose_name_plural': 'dönemsel dağıtımlar',
                'db_table': 'donemsel_dagitim',
                'ordering': ['fatura', 'hesap', 'sira'],
                'constraints': [models.UniqueConstraint(fields=('fatura', 'hesap', 'sira'), name='uq_donemsel_dagitim_sira')],
            },
        ),
    ]
