# Generated by Django 6.0.5 on 2026-10-05 12:03

import core.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0170_cari_virman'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='yevmiyefisi',
            name='kaynak',
            field=models.CharField(choices=[('MANUEL', 'Manuel'), ('FATURA', 'Fatura (otomatik)'), ('KASA', 'Kasa Hareketi (otomatik)'), ('BANKA', 'Banka Hareketi (otomatik)'), ('CEK_SENET', 'Çek/Senet Bordrosu (otomatik)'), ('KREDI_KARTI', 'Kredi Kartı Hareketi (otomatik)'), ('KREDI', 'Kredi Hareketi (otomatik)'), ('YATIRIM', 'Yatırım Projesi Aktifleştirme (otomatik)'), ('STOK_SARF', 'Stok Sarf Çıkışı (otomatik)'), ('URETIM', 'Üretim Maliyet Aktarımı (otomatik)'), ('STOK_SATIS', 'Satış Maliyeti (otomatik)'), ('KUR_DEGERLEME', 'Dönem Sonu Kur Değerleme'), ('CARI_KESINTI', 'Cari Kesinti / Masraf (otomatik)'), ('DURAN_VARLIK', 'Duran Varlık Kartı Açılışı (otomatik)'), ('DONEMSEL', 'Dönemsel Dağıtım (otomatik)'), ('CARI_VIRMAN', 'Cari Virman (otomatik)'), ('BORDRO', 'Personel Bordro Tahakkuku (otomatik)')], default='MANUEL', max_length=20, verbose_name='kaynak'),
        ),
        migrations.CreateModel(
            name='PersonelBordro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('yil', models.PositiveSmallIntegerField(verbose_name='dönem yılı')),
                ('ay', models.PositiveSmallIntegerField(verbose_name='dönem ayı')),
                ('tahakkuk_tarihi', models.DateField(verbose_name='tahakkuk tarihi')),
                ('aciklama', models.CharField(blank=True, max_length=200, verbose_name='açıklama')),
                ('dosya', models.FileField(blank=True, storage=core.storage.ozel_depo, upload_to=core.storage.bordro_dosya_yolu, verbose_name='bordro PDF')),
                ('orijinal_ad', models.CharField(blank=True, max_length=255, verbose_name='özgün dosya adı')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'personel bordrosu',
                'verbose_name_plural': 'personel bordroları',
                'db_table': 'personel_bordro',
                'ordering': ['-yil', '-ay', '-id'],
            },
        ),
        migrations.AddField(
            model_name='yevmiyefisi',
            name='personel_bordro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fisler', to='core.personelbordro', verbose_name='kaynak personel bordrosu'),
        ),
        migrations.CreateModel(
            name='PersonelBordroSatir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('brut', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='brüt kazanç')),
                ('sgk_isci', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='SGK işçi payı')),
                ('issizlik_isci', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='işsizlik işçi payı')),
                ('gelir_vergisi', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='gelir vergisi')),
                ('damga_vergisi', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='damga vergisi')),
                ('net', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='net ödenen')),
                ('sgk_isveren', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='SGK işveren (teşvik sonrası net)')),
                ('issizlik_isveren', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='işsizlik işveren')),
                ('bordro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satirlar', to='core.personelbordro', verbose_name='bordro')),
                ('cari', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bordro_satirlari', to='core.cari', verbose_name='personel carisi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('gider_hesap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.hesapplani', verbose_name='gider hesabı')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'bordro satırı',
                'verbose_name_plural': 'bordro satırları',
                'db_table': 'personel_bordro_satir',
                'ordering': ['bordro', 'id'],
            },
        ),
    ]
