# Generated by Django 6.0.5 on 2026-10-05 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0171_personel_bordro'),
    ]

    operations = [
        migrations.AddField(
            model_name='personelbordrosatir',
            name='ad_soyad',
            field=models.CharField(blank=True, max_length=150, verbose_name='ad soyad (cari yok)'),
        ),
        migrations.AlterField(
            model_name='personelbordrosatir',
            name='cari',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bordro_satirlari', to='core.cari', verbose_name='personel carisi'),
        ),
    ]
