# Generated by Django 6.0.5 on 2026-10-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0172_bordro_satir_carisiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='yatirimprojesi',
            name='kapanis_aciklama',
            field=models.TextField(blank=True, verbose_name='kapanış açıklaması'),
        ),
        migrations.AddField(
            model_name='yatirimprojesi',
            name='kapanis_nedeni',
            field=models.CharField(blank=True, choices=[('SATILDI', 'Satıldı'), ('DIGER', 'Diğer')], max_length=10, verbose_name='kapanış nedeni'),
        ),
        migrations.AddField(
            model_name='yatirimprojesi',
            name='kapanis_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='kapanış tarihi'),
        ),
        migrations.AlterField(
            model_name='yatirimprojesi',
            name='durum',
            field=models.CharField(choices=[('DEVAM', 'Devam Ediyor'), ('AKTIFLESTI', 'Aktifleşti'), ('KAPANDI', 'Kapandı')], default='DEVAM', max_length=12, verbose_name='durum'),
        ),
    ]
