# Generated by Django 6.0.5 on 2026-10-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0173_yatirim_projesi_kapandi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kredikarti',
            name='kurus_farki',
            field=models.CharField(choices=[('ILK', 'İlk taksite'), ('SON', 'Son taksite')], default='SON', max_length=3, verbose_name='kuruş farkı'),
        ),
    ]
