# Generated by Django 6.0.5 on 2026-10-06 22:04

import core.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0174_kredi_karti_kurus_farki'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='yevmiyefisi',
            name='kaynak',
            field=models.CharField(choices=[('MANUEL', 'Manuel'), ('FATURA', 'Fatura (otomatik)'), ('KASA', 'Kasa Hareketi (otomatik)'), ('BANKA', 'Banka Hareketi (otomatik)'), ('CEK_SENET', 'Çek/Senet Bordrosu (otomatik)'), ('KREDI_KARTI', 'Kredi Kartı Hareketi (otomatik)'), ('KREDI', 'Kredi Hareketi (otomatik)'), ('YATIRIM', 'Yatırım Projesi Aktifleştirme (otomatik)'), ('STOK_SARF', 'Stok Sarf Çıkışı (otomatik)'), ('URETIM', 'Üretim Maliyet Aktarımı (otomatik)'), ('STOK_SATIS', 'Satış Maliyeti (otomatik)'), ('KUR_DEGERLEME', 'Dönem Sonu Kur Değerleme'), ('CARI_KESINTI', 'Cari Kesinti / Masraf (otomatik)'), ('DURAN_VARLIK', 'Duran Varlık Kartı Açılışı (otomatik)'), ('DONEMSEL', 'Dönemsel Dağıtım (otomatik)'), ('CARI_VIRMAN', 'Cari Virman (otomatik)'), ('BORDRO', 'Personel Bordro Tahakkuku (otomatik)'), ('KDV_MAHSUP', 'KDV Dönem Mahsubu (otomatik)')], default='MANUEL', max_length=20, verbose_name='kaynak'),
        ),
        migrations.CreateModel(
            name='KdvMahsup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('yil', models.PositiveSmallIntegerField(verbose_name='dönem yılı')),
                ('ay', models.PositiveSmallIntegerField(verbose_name='dönem ayı')),
                ('donem_sonu', models.DateField(verbose_name='dönem sonu (fiş tarihi)')),
                ('beyan_devreden', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='beyan: sonraki döneme devreden KDV')),
                ('beyan_odenecek', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='beyan: ödenecek KDV')),
                ('aciklama', models.CharField(blank=True, max_length=200, verbose_name='açıklama')),
                ('dosya', models.FileField(blank=True, storage=core.storage.ozel_depo, upload_to=core.storage.kdv_mahsup_dosya_yolu, verbose_name='beyanname PDF')),
                ('orijinal_ad', models.CharField(blank=True, max_length=255, verbose_name='özgün dosya adı')),
                ('erp_191', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='ERP 191 bakiyesi')),
                ('erp_391', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='ERP 391 bakiyesi')),
                ('erp_190', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='önceki 190 bakiyesi')),
                ('erp_devreden', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='ERP devreden (190+191−391)')),
                ('fark', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='fark (ERP − beyan)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('fark_hesap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.hesapplani', verbose_name='fark hesabı')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'KDV dönem mahsubu',
                'verbose_name_plural': 'KDV dönem mahsupları',
                'db_table': 'kdv_mahsup',
                'ordering': ['-yil', '-ay', '-id'],
            },
        ),
        migrations.AddField(
            model_name='yevmiyefisi',
            name='kdv_mahsup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fisler', to='core.kdvmahsup', verbose_name='kaynak KDV dönem mahsubu'),
        ),
        migrations.AddConstraint(
            model_name='kdvmahsup',
            constraint=models.UniqueConstraint(condition=models.Q(('silindi', False)), fields=('yil', 'ay'), name='uq_kdv_mahsup_donem_aktif'),
        ),
    ]
