# Generated by Django 6.0.5 on 2026-10-06 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0175_kdv_mahsup'),
    ]

    operations = [
        migrations.AddField(
            model_name='duranvarlik',
            name='bolunen_kart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bolunmus_kartlar', to='core.duranvarlik', verbose_name='bölündüğü kart'),
        ),
        migrations.AlterField(
            model_name='duranvarlik',
            name='durum',
            field=models.CharField(choices=[('AKTIF', 'Aktif'), ('PASIF', 'Pasif'), ('SATILDI', 'Satıldı'), ('BOLUNDU', 'Bölündü')], default='AKTIF', max_length=10, verbose_name='durum'),
        ),
    ]
