# Generated by Django 6.0.5 on 2026-10-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0176_duran_varlik_bolme'),
    ]

    operations = [
        migrations.AddField(
            model_name='operasyon',
            name='tam_calistirma',
            field=models.BooleanField(default=False, verbose_name='tam çalıştırma zorunlu (tam boy)'),
        ),
    ]
