# Generated by Django 6.0.5 on 2026-10-09 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0178_operasyon_tam_calistirma_veri'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperasyonYanCikti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('miktar', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='miktar (1 çalıştırma için)')),
                ('boy_mm', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='boy (mm)')),
                ('sira', models.PositiveSmallIntegerField(default=0, verbose_name='sıra')),
            ],
            options={
                'verbose_name': 'operasyon yan çıktısı',
                'verbose_name_plural': 'operasyon yan çıktıları',
                'db_table': 'core_operasyon_yan_cikti',
                'ordering': ['sira', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='operasyon',
            name='boy_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='ana çıktı boyu (mm)'),
        ),
        migrations.AddConstraint(
            model_name='operasyon',
            constraint=models.CheckConstraint(condition=models.Q(('boy_mm__isnull', True), ('boy_mm__gt', 0), _connector='OR'), name='ck_operasyon_boy_mm_gt0'),
        ),
        migrations.AddField(
            model_name='operasyonyancikti',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan'),
        ),
        migrations.AddField(
            model_name='operasyonyancikti',
            name='operasyon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yan_ciktilar', to='core.operasyon'),
        ),
        migrations.AddField(
            model_name='operasyonyancikti',
            name='stok',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='yan_cikti_kullanimlari', to='core.stok', verbose_name='yan çıktı'),
        ),
        migrations.AddField(
            model_name='operasyonyancikti',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen'),
        ),
        migrations.AddConstraint(
            model_name='operasyonyancikti',
            constraint=models.CheckConstraint(condition=models.Q(('miktar__gt', 0)), name='ck_operasyon_yan_cikti_miktar_gt0'),
        ),
        migrations.AddConstraint(
            model_name='operasyonyancikti',
            constraint=models.CheckConstraint(condition=models.Q(('boy_mm__gt', 0)), name='ck_operasyon_yan_cikti_boy_gt0'),
        ),
        migrations.AddConstraint(
            model_name='operasyonyancikti',
            constraint=models.UniqueConstraint(condition=models.Q(('silindi', False)), fields=('operasyon', 'stok'), name='uq_operasyon_yan_cikti_aktif'),
        ),
    ]
