# Generated by Django 6.0.5 on 2026-10-09 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0179_operasyon_yan_cikti'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperasyonKaydiCikti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('miktar', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='giriş miktarı')),
                ('boy_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='boy (mm)')),
                ('pay_orani', models.DecimalField(decimal_places=10, default=1, max_digits=12, verbose_name='maliyet pay oranı')),
                ('ana_mi', models.BooleanField(default=True, verbose_name='ana çıktı')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('kayit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciktilar', to='core.operasyonkaydi')),
                ('stok', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kayit_cikti_satirlari', to='core.stok', verbose_name='çıktı')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'operasyon kaydı çıktısı',
                'verbose_name_plural': 'operasyon kaydı çıktıları',
                'db_table': 'core_operasyon_kaydi_cikti',
                'ordering': ['-ana_mi', 'pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('silindi', False)), fields=('kayit', 'stok'), name='uq_operasyon_kaydi_cikti_aktif'), models.CheckConstraint(condition=models.Q(('pay_orani__gte', 0), ('pay_orani__lte', 1)), name='ck_operasyon_kaydi_cikti_pay_0_1')],
            },
        ),
    ]
