# Generated by Django 6.0.5 on 2026-10-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0180_operasyon_kaydi_cikti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operasyon',
            name='aciklama',
        ),
        migrations.RemoveField(
            model_name='operasyon',
            name='ad',
        ),
        migrations.AlterField(
            model_name='operasyon',
            name='tam_calistirma',
            field=models.BooleanField(default=False, editable=False, verbose_name='tam çalıştırma zorunlu (tam boy)'),
        ),
    ]
