# Generated by Django 6.0.5 on 2026-10-09 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0181_operasyon_ad_aciklama_kaldir'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FasonFiyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('fasoncu_kodu', models.CharField(blank=True, default='', max_length=40, verbose_name='fasoncunun parça kodu')),
                ('birim_fiyat', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='birim fiyat (parça adedi başına)')),
                ('para_birimi', models.CharField(choices=[('TRY', 'TRY'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='TRY', max_length=3, verbose_name='para birimi')),
                ('gecerlilik_baslangic', models.DateField(verbose_name='geçerlilik başlangıcı')),
                ('aktif', models.BooleanField(default=True, verbose_name='aktif')),
                ('cari', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fason_fiyatlari', to='core.cari', verbose_name='fasoncu (cari)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('stok', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fason_fiyatlari', to='core.stok', verbose_name='kesilmiş parça')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'fason fiyatı',
                'verbose_name_plural': 'fason fiyatları',
                'db_table': 'core_fason_fiyat',
                'ordering': ['cari__unvan', 'stok__kod', '-gecerlilik_baslangic'],
                'constraints': [models.CheckConstraint(condition=models.Q(('birim_fiyat__gte', 0)), name='ck_fason_fiyat_gte0'), models.UniqueConstraint(condition=models.Q(('silindi', False)), fields=('cari', 'stok', 'gecerlilik_baslangic'), name='uq_fason_fiyat_cari_stok_tarih_aktif')],
            },
        ),
    ]
