# Generated by Django 6.0.5 on 2026-10-09 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0182_fason_fiyat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='depo',
            name='fason_cari',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fason_depolari', to='core.cari', verbose_name='fasoncu (cari)'),
        ),
        migrations.AddConstraint(
            model_name='depo',
            constraint=models.UniqueConstraint(condition=models.Q(('fason_cari__isnull', False), ('silindi', False)), fields=('fason_cari',), name='uq_depo_fason_cari_aktif'),
        ),
    ]
