# Generated by Django 6.0.5 on 2026-10-09 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0183_depo_fason_cari'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operasyonkaydi',
            name='fason_cari',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fason_operasyon_kayitlari', to='core.cari', verbose_name='fasoncu (cari)'),
        ),
        migrations.AddField(
            model_name='operasyonkaydicikti',
            name='fason_birim_fiyat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='fason birim fiyat'),
        ),
        migrations.AddField(
            model_name='operasyonkaydicikti',
            name='fason_kur',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='fason kur (TL)'),
        ),
        migrations.AddField(
            model_name='operasyonkaydicikti',
            name='fason_para_birimi',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='fason fiyat para birimi'),
        ),
        migrations.AddField(
            model_name='operasyonkaydicikti',
            name='fason_tutar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='fason tutarı (TL)'),
        ),
        migrations.AddField(
            model_name='operasyonkaydicikti',
            name='fason_tutar_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='fason tutarı (USD)'),
        ),
        migrations.CreateModel(
            name='FasonDonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('yil', models.PositiveSmallIntegerField(editable=False, verbose_name='yıl')),
                ('sira', models.PositiveIntegerField(editable=False, verbose_name='sıra')),
                ('no', models.CharField(editable=False, max_length=20, verbose_name='belge no')),
                ('irsaliye_no', models.CharField(blank=True, default='', max_length=50, verbose_name='fasoncunun irsaliye no')),
                ('tarih', models.DateField(verbose_name='tarih')),
                ('aciklama', models.CharField(blank=True, default='', max_length=300, verbose_name='açıklama')),
                ('cari', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fason_donusleri', to='core.cari', verbose_name='fasoncu (cari)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('depo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fason_donusleri', to='core.depo', verbose_name='çıktıların gireceği depo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'fason dönüş',
                'verbose_name_plural': 'fason dönüşler',
                'db_table': 'core_fason_donus',
                'ordering': ['-yil', '-sira'],
            },
        ),
        migrations.AddField(
            model_name='operasyonkaydi',
            name='fason_donus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kayitlar', to='core.fasondonus', verbose_name='fason dönüş belgesi'),
        ),
        migrations.AddConstraint(
            model_name='fasondonus',
            constraint=models.UniqueConstraint(fields=('yil', 'sira'), name='uq_fason_donus_yil_sira'),
        ),
    ]
