# Generated by Django 6.0.5 on 2026-10-09 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0184_fason_donus'),
    ]

    operations = [
        migrations.AddField(
            model_name='fasondonus',
            name='fatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fason_donusleri', to='core.fatura', verbose_name='fason faturası'),
        ),
    ]
