# Generated by Django 6.0.5 on 2026-10-09 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0185_fason_donus_fatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='fasonkesimkaydi',
            name='cari',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fason_kesim_kayitlari', to='core.cari', verbose_name='fasoncu (cari)'),
        ),
    ]
