# Generated by Django 6.0.5 on 2026-10-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0186_fason_kesim_kaydi_cari'),
    ]

    operations = [
        migrations.AddField(
            model_name='operasyonkaydi',
            name='gelen_ana',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='gelen ana çıktı adedi'),
        ),
        migrations.AddField(
            model_name='operasyonkaydi',
            name='gelen_yan',
            field=models.JSONField(blank=True, default=dict, verbose_name='gelen yan çıktı adetleri'),
        ),
        migrations.AddField(
            model_name='operasyonkaydicikti',
            name='beklenen_miktar',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='beklenen miktar'),
        ),
    ]
