# Generated by Django 6.0.5 on 2026-10-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0187_fason_gelen_adet_fire'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='hizmet_kategorisi',
            field=models.BooleanField(default=False, verbose_name='hizmet kategorisi (stok hareketi yapmaz)'),
        ),
    ]
