# Generated by Django 6.0.5 on 2026-10-09 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0188_kategori_hizmet'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fasonkesim',
            name='ck_fason_kesim_adet_gte1',
        ),
        migrations.RemoveConstraint(
            model_name='fasonkesim',
            name='uq_fason_kesim_urun_parca_aktif',
        ),
        migrations.RemoveConstraint(
            model_name='fasonkesimkaydi',
            name='uq_fason_kesim_kaydi_yil_sira',
        ),
        migrations.RemoveConstraint(
            model_name='fasonkesimkaydikalemi',
            name='ck_fason_kesim_kaydi_kalemi_miktar_gte1',
        ),
        migrations.RemoveField(
            model_name='stok',
            name='kesildigi_profil',
        ),
        migrations.RemoveField(
            model_name='fasonkesimkaydi',
            name='cari',
        ),
        migrations.RemoveField(
            model_name='fasonkesimkaydi',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='fasonkesimkaydi',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='fasonkesimkaydikalemi',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='fasonkesimkaydikalemi',
            name='kayit',
        ),
        migrations.RemoveField(
            model_name='fasonkesimkaydikalemi',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='fasonkesimkaydikalemi',
            name='urun',
        ),
        migrations.DeleteModel(
            name='FasonKesim',
        ),
        migrations.DeleteModel(
            name='FasonKesimKaydi',
        ),
        migrations.DeleteModel(
            name='FasonKesimKaydiKalemi',
        ),
    ]
