# Generated by Django 6.0.5 on 2026-10-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0190_fason_kesim_yetki_temizle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operasyon',
            name='tam_calistirma',
            field=models.BooleanField(default=False, verbose_name='tam çalıştırma zorunlu (tam boy)'),
        ),
        migrations.AlterField(
            model_name='operasyongirdi',
            name='miktar',
            field=models.DecimalField(decimal_places=6, max_digits=18, verbose_name='miktar (1 çalıştırma için)'),
        ),
        migrations.AlterField(
            model_name='operasyonkaydi',
            name='gelen_ana',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='gelen ana çıktı adedi'),
        ),
        migrations.AlterField(
            model_name='operasyonkaydi',
            name='hedef_cikti_miktari',
            field=models.DecimalField(decimal_places=6, max_digits=18, verbose_name='hedef çıktı miktarı'),
        ),
        migrations.AlterField(
            model_name='operasyonkaydicikti',
            name='beklenen_miktar',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='beklenen miktar'),
        ),
        migrations.AlterField(
            model_name='operasyonkaydicikti',
            name='miktar',
            field=models.DecimalField(decimal_places=6, max_digits=18, verbose_name='giriş miktarı'),
        ),
        migrations.AlterField(
            model_name='operasyonkaydigirdi',
            name='gerceklesen_miktar',
            field=models.DecimalField(decimal_places=6, max_digits=18, verbose_name='gerçekleşen miktar'),
        ),
        migrations.AlterField(
            model_name='operasyonkaydigirdi',
            name='planlanan_miktar',
            field=models.DecimalField(decimal_places=6, max_digits=18, verbose_name='planlanan miktar'),
        ),
        migrations.AlterField(
            model_name='operasyonyancikti',
            name='miktar',
            field=models.DecimalField(decimal_places=6, max_digits=18, verbose_name='miktar (1 çalıştırma için)'),
        ),
        migrations.AlterField(
            model_name='stok',
            name='maliyet_miktar',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='maliyet miktarı (önbellek)'),
        ),
        migrations.AlterField(
            model_name='stokhareket',
            name='miktar',
            field=models.DecimalField(decimal_places=6, max_digits=18, verbose_name='miktar'),
        ),
        migrations.AlterField(
            model_name='stokhareket',
            name='sonrasi_miktar',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='hareket sonrası miktar'),
        ),
        migrations.AlterField(
            model_name='stokmaliyetkatmani',
            name='giris_miktar',
            field=models.DecimalField(decimal_places=6, max_digits=18, verbose_name='giriş miktarı'),
        ),
        migrations.AlterField(
            model_name='stokmaliyetkatmani',
            name='kalan_miktar',
            field=models.DecimalField(decimal_places=6, max_digits=18, verbose_name='kalan miktar'),
        ),
        migrations.AlterField(
            model_name='stokmaliyettuketimi',
            name='miktar',
            field=models.DecimalField(decimal_places=6, max_digits=18, verbose_name='miktar'),
        ),
    ]
