# Generated by Django 6.0.5 on 2026-10-09 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0191_tam_boy_secmeli_miktar_6_ondalik'),
    ]

    operations = [
        migrations.AddField(
            model_name='cari',
            name='fason_faturasiz',
            field=models.BooleanField(default=False, verbose_name='faturasız fason (dönüş onayında cariye yaz)'),
        ),
        migrations.AddField(
            model_name='fasondonus',
            name='tahakkuk_fis',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fason_tahakkuk_donusleri', to='core.yevmiyefisi', verbose_name='fason tahakkuk fişi'),
        ),
        migrations.AlterField(
            model_name='yevmiyefisi',
            name='kaynak',
            field=models.CharField(choices=[('MANUEL', 'Manuel'), ('FATURA', 'Fatura (otomatik)'), ('KASA', 'Kasa Hareketi (otomatik)'), ('BANKA', 'Banka Hareketi (otomatik)'), ('CEK_SENET', 'Çek/Senet Bordrosu (otomatik)'), ('KREDI_KARTI', 'Kredi Kartı Hareketi (otomatik)'), ('KREDI', 'Kredi Hareketi (otomatik)'), ('YATIRIM', 'Yatırım Projesi Aktifleştirme (otomatik)'), ('STOK_SARF', 'Stok Sarf Çıkışı (otomatik)'), ('URETIM', 'Üretim Maliyet Aktarımı (otomatik)'), ('STOK_SATIS', 'Satış Maliyeti (otomatik)'), ('KUR_DEGERLEME', 'Dönem Sonu Kur Değerleme'), ('CARI_KESINTI', 'Cari Kesinti / Masraf (otomatik)'), ('DURAN_VARLIK', 'Duran Varlık Kartı Açılışı (otomatik)'), ('DONEMSEL', 'Dönemsel Dağıtım (otomatik)'), ('CARI_VIRMAN', 'Cari Virman (otomatik)'), ('BORDRO', 'Personel Bordro Tahakkuku (otomatik)'), ('KDV_MAHSUP', 'KDV Dönem Mahsubu (otomatik)'), ('FASON_TAHAKKUK', 'Fason Tahakkuku (otomatik)')], default='MANUEL', max_length=20, verbose_name='kaynak'),
        ),
    ]
