# Generated by Django 6.0.5 on 2026-10-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0192_fason_faturasiz_tahakkuk'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturatipi',
            name='yalniz_kdv',
            field=models.BooleanField(default=False, verbose_name='yalnız KDV (matrah fişe yazılmaz)'),
        ),
    ]
