# Generated by Django 6.0.5 on 2026-10-09 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0193_fatura_tipi_yalniz_kdv'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operasyon',
            name='pay_anahtari',
            field=models.CharField(choices=[('BOY', 'Boy oranı (miktar × boy)'), ('ESIT', 'Eşit (adet başı)'), ('YUZDE', 'Yüzde (elle)')], default='BOY', max_length=5, verbose_name='maliyet pay anahtarı'),
        ),
        migrations.AddField(
            model_name='operasyon',
            name='tur',
            field=models.CharField(choices=[('URET', 'Üret (N girdi → 1 çıktı)'), ('PARCALA', 'Parçala (1 girdi → N çıktı)')], default='URET', max_length=7, verbose_name='tür'),
        ),
        migrations.AddField(
            model_name='operasyonkaydicikti',
            name='agirlik',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True, verbose_name='paylaştırma ağırlığı'),
        ),
        migrations.CreateModel(
            name='OperasyonCikti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('miktar', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='miktar (1 çalıştırma için)')),
                ('boy_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='boy (mm)')),
                ('yuzde', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='maliyet payı (%)')),
                ('sira', models.PositiveSmallIntegerField(default=0, verbose_name='sıra')),
                ('surucu', models.BooleanField(default=True, verbose_name='bu tanımdan üretilir')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('operasyon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciktilar', to='core.operasyon')),
                ('stok', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operasyon_cikti_satirlari', to='core.stok', verbose_name='çıktı')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
            ],
            options={
                'verbose_name': 'operasyon çıktısı',
                'verbose_name_plural': 'operasyon çıktıları',
                'db_table': 'core_operasyon_cikti',
                'ordering': ['sira', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('miktar__gt', 0)), name='ck_op_cikti_satir_miktar_gt0'), models.CheckConstraint(condition=models.Q(('boy_mm__isnull', True), ('boy_mm__gt', 0), _connector='OR'), name='ck_op_cikti_satir_boy_gt0'), models.CheckConstraint(condition=models.Q(('yuzde__isnull', True), models.Q(('yuzde__gt', 0), ('yuzde__lte', 100)), _connector='OR'), name='ck_op_cikti_satir_yuzde_0_100'), models.UniqueConstraint(condition=models.Q(('silindi', False)), fields=('operasyon', 'stok'), name='uq_operasyon_cikti_aktif_op_stok'), models.UniqueConstraint(condition=models.Q(('silindi', False), ('surucu', True)), fields=('stok',), name='uq_operasyon_cikti_surucu_aktif')],
            },
        ),
    ]
