"""Üretim siparişi stok ayırma (rezervasyon) — SAF ŞEMA: ``StokAyirma`` tablosu (adım 1, bkz. docs/uretim-siparisi-plan.md). Veri yok."""
# Generated by Django 6.0.5 on 2026-10-10 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0197_operasyon_yan_cikti_kaldir'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StokAyirma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('miktar', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='ayrılan miktar')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('stok', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ayirmalar', to='core.stok', verbose_name='stok')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
                ('uretim_emri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayirmalar', to='core.uretimemri', verbose_name='üretim siparişi')),
            ],
            options={
                'verbose_name': 'stok ayırması',
                'verbose_name_plural': 'stok ayırmaları',
                'db_table': 'core_stok_ayirma',
                'ordering': ['uretim_emri', 'stok__kod'],
                'constraints': [models.CheckConstraint(condition=models.Q(('miktar__gte', 0)), name='ck_stok_ayirma_miktar_gte0'), models.UniqueConstraint(condition=models.Q(('silindi', False)), fields=('uretim_emri', 'stok'), name='uq_stok_ayirma_aktif')],
            },
        ),
    ]
