# Generated by Django 6.0.5 on 2026-10-10 10:05

"""Üretim siparişi — SAF ŞEMA (adım 3, bkz. docs/uretim-siparisi-plan.md): UretimEmri durum/revizyon_no/kapanis_tarihi, UretimEmriKalemi
siparis_kalem/eldeki_ayrilan, yeni IstasyonEmri ve UretimEmriRevizyon tabloları, OperasyonKaydi.istasyon_emri. Veri yok (mevcut emirler ACIK
varsayılanıyla kalır)."""
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0198_stok_ayirma'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uretimemri',
            options={'ordering': ['-yil', '-sira'], 'verbose_name': 'üretim siparişi', 'verbose_name_plural': 'üretim siparişleri'},
        ),
        migrations.AddField(
            model_name='uretimemri',
            name='durum',
            field=models.CharField(choices=[('ACIK', 'Açık'), ('KAPALI', 'Kapalı'), ('IPTAL', 'İptal')], default='ACIK', max_length=6, verbose_name='durum'),
        ),
        migrations.AddField(
            model_name='uretimemri',
            name='kapanis_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='kapanış tarihi'),
        ),
        migrations.AddField(
            model_name='uretimemri',
            name='revizyon_no',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='revizyon no'),
        ),
        migrations.AddField(
            model_name='uretimemrikalemi',
            name='eldeki_ayrilan',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='eldekinden ayrılan'),
        ),
        migrations.AddField(
            model_name='uretimemrikalemi',
            name='siparis_kalem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uretim_emri_kalemleri', to='core.teklifsipariskalem', verbose_name='sipariş kalemi'),
        ),
        migrations.CreateModel(
            name='IstasyonEmri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('yil', models.PositiveSmallIntegerField(editable=False, verbose_name='yıl')),
                ('sira', models.PositiveIntegerField(editable=False, verbose_name='sıra')),
                ('no', models.CharField(editable=False, max_length=20, verbose_name='emir no')),
                ('seviye', models.PositiveSmallIntegerField(default=0, verbose_name='seviye (zincir sırası)')),
                ('planlanan', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='planlanan çalıştırma')),
                ('tamamlanan', models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='tamamlanan çalıştırma')),
                ('durum', models.CharField(choices=[('BEKLIYOR', 'Bekliyor'), ('BASLADI', 'Başladı'), ('BITTI', 'Bitti'), ('IPTAL', 'İptal')], default='BEKLIYOR', max_length=8, verbose_name='durum')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('istasyon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emirler', to='core.isistasyonu', verbose_name='iş istasyonu')),
                ('operasyon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='istasyon_emirleri', to='core.operasyon', verbose_name='operasyon')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
                ('uretim_emri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='istasyon_emirleri', to='core.uretimemri', verbose_name='üretim siparişi')),
            ],
            options={
                'verbose_name': 'istasyon emri',
                'verbose_name_plural': 'istasyon emirleri',
                'db_table': 'core_istasyon_emri',
                'ordering': ['uretim_emri', 'seviye', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='operasyonkaydi',
            name='istasyon_emri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kayitlar', to='core.istasyonemri', verbose_name='istasyon emri'),
        ),
        migrations.CreateModel(
            name='UretimEmriRevizyon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('silindi', models.BooleanField(default=False, verbose_name='silindi (soft delete)')),
                ('silindi_at', models.DateTimeField(blank=True, null=True, verbose_name='silinme zamanı')),
                ('no', models.PositiveSmallIntegerField(verbose_name='sıra no')),
                ('tur', models.CharField(choices=[('ACILIS', 'Açılış'), ('REVIZE', 'Revize'), ('KAPANIS', 'Kapanış'), ('YENIDEN_ACILIS', 'Yeniden açılış'), ('IPTAL', 'İptal')], max_length=14, verbose_name='tür')),
                ('tarih', models.DateField(verbose_name='tarih')),
                ('aciklama', models.CharField(blank=True, default='', max_length=300, verbose_name='açıklama')),
                ('detay', models.JSONField(blank=True, default=dict, verbose_name='detay (önce/sonra)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='güncelleyen')),
                ('uretim_emri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revizyonlar', to='core.uretimemri', verbose_name='üretim siparişi')),
            ],
            options={
                'verbose_name': 'üretim siparişi revizyonu',
                'verbose_name_plural': 'üretim siparişi revizyonları',
                'db_table': 'core_uretim_emri_revizyon',
                'ordering': ['uretim_emri', 'no'],
            },
        ),
        migrations.AddConstraint(
            model_name='istasyonemri',
            constraint=models.UniqueConstraint(fields=('yil', 'sira'), name='uq_istasyon_emri_yil_sira'),
        ),
        migrations.AddConstraint(
            model_name='istasyonemri',
            constraint=models.UniqueConstraint(condition=models.Q(('silindi', False)), fields=('uretim_emri', 'operasyon'), name='uq_istasyon_emri_aktif_op'),
        ),
        migrations.AddConstraint(
            model_name='istasyonemri',
            constraint=models.CheckConstraint(condition=models.Q(('planlanan__gte', 0)), name='ck_istasyon_emri_planlanan_gte0'),
        ),
        migrations.AddConstraint(
            model_name='istasyonemri',
            constraint=models.CheckConstraint(condition=models.Q(('tamamlanan__gte', 0)), name='ck_istasyon_emri_tamamlanan_gte0'),
        ),
        migrations.AddConstraint(
            model_name='uretimemrirevizyon',
            constraint=models.UniqueConstraint(fields=('uretim_emri', 'no'), name='uq_uretim_emri_revizyon_no'),
        ),
    ]
