"""Üretim siparişi adım 5 — SAF ŞEMA iz alanları: IstasyonEmri.ihtiyac, OperasyonKaydiCikti.ayrilan, OperasyonKaydiGirdi.ayrilan_dusen (bkz. docs/uretim-siparisi-plan.md)."""
# Generated by Django 6.0.5 on 2026-10-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0199_uretim_siparisi_sema'),
    ]

    operations = [
        migrations.AddField(
            model_name='istasyonemri',
            name='ihtiyac',
            field=models.JSONField(blank=True, default=dict, verbose_name='net ihtiyaç ({stok pk: miktar})'),
        ),
        migrations.AddField(
            model_name='operasyonkaydicikti',
            name='ayrilan',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='üretim siparişine ayrılan'),
        ),
        migrations.AddField(
            model_name='operasyonkaydigirdi',
            name='ayrilan_dusen',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='ayırmadan düşen'),
        ),
    ]
