"""Üretim siparişi adım 8 — SAF ŞEMA: UretimEmri.sevk_dusen (sevk nedeniyle ayırmadan düşen miktarlar; bkz. docs/uretim-siparisi-plan.md)."""
# Generated by Django 6.0.5 on 2026-10-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0200_uretim_siparisi_ayirma_izi'),
    ]

    operations = [
        migrations.AddField(
            model_name='uretimemri',
            name='sevk_dusen',
            field=models.JSONField(blank=True, default=dict, verbose_name='sevk nedeniyle ayırmadan düşen ({stok pk: miktar})'),
        ),
    ]
