# Generated by Django 6.0.5 on 2026-10-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0201_uretim_emri_sevk_dusen'),
    ]

    operations = [
        migrations.AddField(
            model_name='depo',
            name='aktif',
            field=models.BooleanField(default=True, verbose_name='aktif'),
        ),
    ]
