from django.urls import path

from core import views

app_name = "core"

urlpatterns = [
    path("", views.pano, name="pano"),
    path("fis-gir/", views.fis_ekle, name="fis_ekle"),
    path("fisler/", views.fis_listesi, name="fis_listesi"),
    path("kurlar/", views.kurlar, name="kurlar"),
    path("api/kur-usd/", views.kur_usd_api, name="kur_usd_api"),
    path("hesap-plani/", views.hesap_plani, name="hesap_plani"),
    path("hesap-plani/ekle/", views.hesap_ekle, name="hesap_ekle"),
    path("hesap-plani/<str:kod>/ad/", views.hesap_ad_guncelle, name="hesap_ad_guncelle"),
    path("hesap-plani/<str:kod>/sil/", views.hesap_sil, name="hesap_sil"),
    path("fis/<int:pk>/", views.fis_detay, name="fis_detay"),
    path("fis/<int:pk>/duzenle/", views.fis_duzenle, name="fis_duzenle"),
    path("fis/<int:pk>/iptal/", views.fis_iptal_gorunum, name="fis_iptal"),
    path("mizan/", views.mizan_gorunum, name="mizan"),
    path("ekstre/<str:hesap_kodu>/", views.hesap_ekstresi, name="hesap_ekstresi"),
    path("bilanco/", views.bilanco_gorunum, name="bilanco"),
    path("gelir-tablosu/", views.gelir_tablosu_gorunum, name="gelir_tablosu"),
    path("mizan-usd/", views.mizan_usd_gorunum, name="mizan_usd"),
    path("bilanco-usd/", views.bilanco_usd_gorunum, name="bilanco_usd"),
    path("gelir-tablosu-usd/", views.gelir_tablosu_usd_gorunum, name="gelir_tablosu_usd"),
    # Ayarlar modülü (yalnızca yönetici)
    path("kullanicilar/", views.kullanici_listesi, name="kullanici_listesi"),
    path("kullanicilar/ekle/", views.kullanici_ekle, name="kullanici_ekle"),
    path("kullanicilar/<int:pk>/duzenle/", views.kullanici_duzenle, name="kullanici_duzenle"),
    path("ayarlar/kullanici-yetkileri/", views.kullanici_yetkileri, name="kullanici_yetkileri"),
    path("ayarlar/yedek/", views.yedek_yonetim, name="yedek"),
    path("ayarlar/yedek/indir/<str:ad>/", views.yedek_indir, name="yedek_indir"),
    # STOKLAR modülü
    path("stoklar/", views.stoklar, name="stoklar"),
    path("stoklar/ekle/", views.stok_ekle, name="stok_ekle"),
    path("api/stok-kod/", views.stok_kod_api, name="stok_kod_api"),
    path("stoklar/<int:pk>/", views.stok_detay, name="stok_detay"),
    path("stoklar/<int:pk>/duzenle/", views.stok_duzenle, name="stok_duzenle"),
    path("stoklar/<int:pk>/sil/", views.stok_sil, name="stok_sil"),
    path("stoklar/kategoriler/", views.kategoriler, name="kategoriler"),
    path("stoklar/kategoriler/ekle/", views.kategori_ekle, name="kategori_ekle"),
    path("stoklar/kategoriler/<int:pk>/duzenle/", views.kategori_duzenle, name="kategori_duzenle"),
    path("stoklar/kategoriler/<int:pk>/sil/", views.kategori_sil, name="kategori_sil"),
    path("stoklar/fatura-tipleri/", views.fatura_tipleri, name="fatura_tipleri"),
    path("stoklar/fatura-tipleri/ekle/", views.fatura_tipi_ekle, name="fatura_tipi_ekle"),
    path("stoklar/fatura-tipleri/<int:pk>/duzenle/", views.fatura_tipi_duzenle, name="fatura_tipi_duzenle"),
    path("stoklar/fatura-tipleri/<int:pk>/sil/", views.fatura_tipi_sil, name="fatura_tipi_sil"),
    path("stoklar/birimler/", views.birimler, name="birimler"),
    path("stoklar/birimler/ekle/", views.birim_ekle, name="birim_ekle"),
    path("stoklar/birimler/<int:pk>/duzenle/", views.birim_duzenle, name="birim_duzenle"),
    path("stoklar/birimler/<int:pk>/sil/", views.birim_sil, name="birim_sil"),
    # CARİLER modülü — Ülke / Şehir
    path("cariler/lokasyonlar/", views.lokasyonlar, name="lokasyonlar"),
    path("cariler/ulke/ekle/", views.ulke_ekle, name="ulke_ekle"),
    path("cariler/ulke/<int:pk>/duzenle/", views.ulke_duzenle, name="ulke_duzenle"),
    path("cariler/ulke/<int:pk>/sil/", views.ulke_sil, name="ulke_sil"),
    path("cariler/sehir/ekle/", views.sehir_ekle, name="sehir_ekle"),
    path("cariler/sehir/<int:pk>/duzenle/", views.sehir_duzenle, name="sehir_duzenle"),
    path("cariler/sehir/<int:pk>/sil/", views.sehir_sil, name="sehir_sil"),
]
